// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: protoconf/v1/protoconf.proto

package protoconf_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtoconfService_SubscribeForConfig_FullMethodName = "/protoconf.v1.ProtoconfService/SubscribeForConfig"
	ProtoconfService_GetConfig_FullMethodName          = "/protoconf.v1.ProtoconfService/GetConfig"
)

// ProtoconfServiceClient is the client API for ProtoconfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoconfServiceClient interface {
	SubscribeForConfig(ctx context.Context, in *ConfigSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error)
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigUpdate, error)
}

type protoconfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoconfServiceClient(cc grpc.ClientConnInterface) ProtoconfServiceClient {
	return &protoconfServiceClient{cc}
}

func (c *protoconfServiceClient) SubscribeForConfig(ctx context.Context, in *ConfigSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProtoconfService_ServiceDesc.Streams[0], ProtoconfService_SubscribeForConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigSubscriptionRequest, ConfigUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtoconfService_SubscribeForConfigClient = grpc.ServerStreamingClient[ConfigUpdate]

func (c *protoconfServiceClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigUpdate)
	err := c.cc.Invoke(ctx, ProtoconfService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoconfServiceServer is the server API for ProtoconfService service.
// All implementations must embed UnimplementedProtoconfServiceServer
// for forward compatibility.
type ProtoconfServiceServer interface {
	SubscribeForConfig(*ConfigSubscriptionRequest, grpc.ServerStreamingServer[ConfigUpdate]) error
	GetConfig(context.Context, *ConfigRequest) (*ConfigUpdate, error)
	mustEmbedUnimplementedProtoconfServiceServer()
}

// UnimplementedProtoconfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoconfServiceServer struct{}

func (UnimplementedProtoconfServiceServer) SubscribeForConfig(*ConfigSubscriptionRequest, grpc.ServerStreamingServer[ConfigUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeForConfig not implemented")
}
func (UnimplementedProtoconfServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedProtoconfServiceServer) mustEmbedUnimplementedProtoconfServiceServer() {}
func (UnimplementedProtoconfServiceServer) testEmbeddedByValue()                          {}

// UnsafeProtoconfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoconfServiceServer will
// result in compilation errors.
type UnsafeProtoconfServiceServer interface {
	mustEmbedUnimplementedProtoconfServiceServer()
}

func RegisterProtoconfServiceServer(s grpc.ServiceRegistrar, srv ProtoconfServiceServer) {
	// If the following call pancis, it indicates UnimplementedProtoconfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoconfService_ServiceDesc, srv)
}

func _ProtoconfService_SubscribeForConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigSubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProtoconfServiceServer).SubscribeForConfig(m, &grpc.GenericServerStream[ConfigSubscriptionRequest, ConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtoconfService_SubscribeForConfigServer = grpc.ServerStreamingServer[ConfigUpdate]

func _ProtoconfService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoconfServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoconfService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoconfServiceServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoconfService_ServiceDesc is the grpc.ServiceDesc for ProtoconfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoconfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoconf.v1.ProtoconfService",
	HandlerType: (*ProtoconfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ProtoconfService_GetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeForConfig",
			Handler:       _ProtoconfService_SubscribeForConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protoconf/v1/protoconf.proto",
}

const (
	ProtoconfMutationService_MutateConfig_FullMethodName = "/protoconf.v1.ProtoconfMutationService/MutateConfig"
)

// ProtoconfMutationServiceClient is the client API for ProtoconfMutationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoconfMutationServiceClient interface {
	MutateConfig(ctx context.Context, in *ConfigMutationRequest, opts ...grpc.CallOption) (*ConfigMutationResponse, error)
}

type protoconfMutationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoconfMutationServiceClient(cc grpc.ClientConnInterface) ProtoconfMutationServiceClient {
	return &protoconfMutationServiceClient{cc}
}

func (c *protoconfMutationServiceClient) MutateConfig(ctx context.Context, in *ConfigMutationRequest, opts ...grpc.CallOption) (*ConfigMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMutationResponse)
	err := c.cc.Invoke(ctx, ProtoconfMutationService_MutateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoconfMutationServiceServer is the server API for ProtoconfMutationService service.
// All implementations must embed UnimplementedProtoconfMutationServiceServer
// for forward compatibility.
type ProtoconfMutationServiceServer interface {
	MutateConfig(context.Context, *ConfigMutationRequest) (*ConfigMutationResponse, error)
	mustEmbedUnimplementedProtoconfMutationServiceServer()
}

// UnimplementedProtoconfMutationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoconfMutationServiceServer struct{}

func (UnimplementedProtoconfMutationServiceServer) MutateConfig(context.Context, *ConfigMutationRequest) (*ConfigMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MutateConfig not implemented")
}
func (UnimplementedProtoconfMutationServiceServer) mustEmbedUnimplementedProtoconfMutationServiceServer() {
}
func (UnimplementedProtoconfMutationServiceServer) testEmbeddedByValue() {}

// UnsafeProtoconfMutationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoconfMutationServiceServer will
// result in compilation errors.
type UnsafeProtoconfMutationServiceServer interface {
	mustEmbedUnimplementedProtoconfMutationServiceServer()
}

func RegisterProtoconfMutationServiceServer(s grpc.ServiceRegistrar, srv ProtoconfMutationServiceServer) {
	// If the following call pancis, it indicates UnimplementedProtoconfMutationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoconfMutationService_ServiceDesc, srv)
}

func _ProtoconfMutationService_MutateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoconfMutationServiceServer).MutateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoconfMutationService_MutateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoconfMutationServiceServer).MutateConfig(ctx, req.(*ConfigMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoconfMutationService_ServiceDesc is the grpc.ServiceDesc for ProtoconfMutationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoconfMutationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoconf.v1.ProtoconfMutationService",
	HandlerType: (*ProtoconfMutationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MutateConfig",
			Handler:    _ProtoconfMutationService_MutateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoconf/v1/protoconf.proto",
}

const (
	ProtoconfMutationReportService_ReportProgress_FullMethodName = "/protoconf.v1.ProtoconfMutationReportService/ReportProgress"
)

// ProtoconfMutationReportServiceClient is the client API for ProtoconfMutationReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoconfMutationReportServiceClient interface {
	ReportProgress(ctx context.Context, in *ConfigMutationResponse, opts ...grpc.CallOption) (*ConfigMutationResponse, error)
}

type protoconfMutationReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoconfMutationReportServiceClient(cc grpc.ClientConnInterface) ProtoconfMutationReportServiceClient {
	return &protoconfMutationReportServiceClient{cc}
}

func (c *protoconfMutationReportServiceClient) ReportProgress(ctx context.Context, in *ConfigMutationResponse, opts ...grpc.CallOption) (*ConfigMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMutationResponse)
	err := c.cc.Invoke(ctx, ProtoconfMutationReportService_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoconfMutationReportServiceServer is the server API for ProtoconfMutationReportService service.
// All implementations must embed UnimplementedProtoconfMutationReportServiceServer
// for forward compatibility.
type ProtoconfMutationReportServiceServer interface {
	ReportProgress(context.Context, *ConfigMutationResponse) (*ConfigMutationResponse, error)
	mustEmbedUnimplementedProtoconfMutationReportServiceServer()
}

// UnimplementedProtoconfMutationReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoconfMutationReportServiceServer struct{}

func (UnimplementedProtoconfMutationReportServiceServer) ReportProgress(context.Context, *ConfigMutationResponse) (*ConfigMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedProtoconfMutationReportServiceServer) mustEmbedUnimplementedProtoconfMutationReportServiceServer() {
}
func (UnimplementedProtoconfMutationReportServiceServer) testEmbeddedByValue() {}

// UnsafeProtoconfMutationReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoconfMutationReportServiceServer will
// result in compilation errors.
type UnsafeProtoconfMutationReportServiceServer interface {
	mustEmbedUnimplementedProtoconfMutationReportServiceServer()
}

func RegisterProtoconfMutationReportServiceServer(s grpc.ServiceRegistrar, srv ProtoconfMutationReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedProtoconfMutationReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoconfMutationReportService_ServiceDesc, srv)
}

func _ProtoconfMutationReportService_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigMutationResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoconfMutationReportServiceServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoconfMutationReportService_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoconfMutationReportServiceServer).ReportProgress(ctx, req.(*ConfigMutationResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoconfMutationReportService_ServiceDesc is the grpc.ServiceDesc for ProtoconfMutationReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoconfMutationReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoconf.v1.ProtoconfMutationReportService",
	HandlerType: (*ProtoconfMutationReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportProgress",
			Handler:    _ProtoconfMutationReportService_ReportProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoconf/v1/protoconf.proto",
}

const (
	ProtoconfCompile_CompileFiles_FullMethodName = "/protoconf.v1.ProtoconfCompile/CompileFiles"
)

// ProtoconfCompileClient is the client API for ProtoconfCompile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoconfCompileClient interface {
	CompileFiles(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompileResponse], error)
}

type protoconfCompileClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoconfCompileClient(cc grpc.ClientConnInterface) ProtoconfCompileClient {
	return &protoconfCompileClient{cc}
}

func (c *protoconfCompileClient) CompileFiles(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProtoconfCompile_ServiceDesc.Streams[0], ProtoconfCompile_CompileFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompileRequest, CompileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtoconfCompile_CompileFilesClient = grpc.ServerStreamingClient[CompileResponse]

// ProtoconfCompileServer is the server API for ProtoconfCompile service.
// All implementations must embed UnimplementedProtoconfCompileServer
// for forward compatibility.
type ProtoconfCompileServer interface {
	CompileFiles(*CompileRequest, grpc.ServerStreamingServer[CompileResponse]) error
	mustEmbedUnimplementedProtoconfCompileServer()
}

// UnimplementedProtoconfCompileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoconfCompileServer struct{}

func (UnimplementedProtoconfCompileServer) CompileFiles(*CompileRequest, grpc.ServerStreamingServer[CompileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CompileFiles not implemented")
}
func (UnimplementedProtoconfCompileServer) mustEmbedUnimplementedProtoconfCompileServer() {}
func (UnimplementedProtoconfCompileServer) testEmbeddedByValue()                          {}

// UnsafeProtoconfCompileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoconfCompileServer will
// result in compilation errors.
type UnsafeProtoconfCompileServer interface {
	mustEmbedUnimplementedProtoconfCompileServer()
}

func RegisterProtoconfCompileServer(s grpc.ServiceRegistrar, srv ProtoconfCompileServer) {
	// If the following call pancis, it indicates UnimplementedProtoconfCompileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoconfCompile_ServiceDesc, srv)
}

func _ProtoconfCompile_CompileFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProtoconfCompileServer).CompileFiles(m, &grpc.GenericServerStream[CompileRequest, CompileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtoconfCompile_CompileFilesServer = grpc.ServerStreamingServer[CompileResponse]

// ProtoconfCompile_ServiceDesc is the grpc.ServiceDesc for ProtoconfCompile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoconfCompile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoconf.v1.ProtoconfCompile",
	HandlerType: (*ProtoconfCompileServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompileFiles",
			Handler:       _ProtoconfCompile_CompileFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protoconf/v1/protoconf.proto",
}
