// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protoconf/v1/protoconf.proto

package protoconf_pb

import (
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoconfValue struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ProtoFile     string                        `protobuf:"bytes,1,opt,name=proto_file,json=protoFile,proto3" json:"proto_file,omitempty"`
	Value         *anypb.Any                    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RolloutConfig *ProtoconfValue_ConfigRollout `protobuf:"bytes,3,opt,name=rollout_config,json=rolloutConfig,proto3" json:"rollout_config,omitempty"`
	Metadata      *Metadata                     `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoconfValue) Reset() {
	*x = ProtoconfValue{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoconfValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoconfValue) ProtoMessage() {}

func (x *ProtoconfValue) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoconfValue.ProtoReflect.Descriptor instead.
func (*ProtoconfValue) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoconfValue) GetProtoFile() string {
	if x != nil {
		return x.ProtoFile
	}
	return ""
}

func (x *ProtoconfValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProtoconfValue) GetRolloutConfig() *ProtoconfValue_ConfigRollout {
	if x != nil {
		return x.RolloutConfig
	}
	return nil
}

func (x *ProtoconfValue) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Agent
type Metadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Commit         string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	CommitterEmail string                 `protobuf:"bytes,2,opt,name=committer_email,json=committerEmail,proto3" json:"committer_email,omitempty"`
	AuthorEmail    string                 `protobuf:"bytes,3,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	CommittedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	AuthoredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=authored_at,json=authoredAt,proto3" json:"authored_at,omitempty"`
	InsertedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=inserted_at,json=insertedAt,proto3" json:"inserted_at,omitempty"`
	Channel        string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Metadata) GetCommitterEmail() string {
	if x != nil {
		return x.CommitterEmail
	}
	return ""
}

func (x *Metadata) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Metadata) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

func (x *Metadata) GetAuthoredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthoredAt
	}
	return nil
}

func (x *Metadata) GetInsertedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InsertedAt
	}
	return nil
}

func (x *Metadata) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ConfigSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSubscriptionRequest) Reset() {
	*x = ConfigSubscriptionRequest{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSubscriptionRequest) ProtoMessage() {}

func (x *ConfigSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ConfigSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigSubscriptionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigSubscriptionRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Raw           *httpbody.HttpBody     `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigUpdate) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConfigUpdate) GetRaw() *httpbody.HttpBody {
	if x != nil {
		return x.Raw
	}
	return nil
}

// Mutation Server
type ConfigMutationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value          *ProtoconfValue        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ScriptMetadata string                 `protobuf:"bytes,3,opt,name=script_metadata,json=scriptMetadata,proto3" json:"script_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigMutationRequest) Reset() {
	*x = ConfigMutationRequest{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMutationRequest) ProtoMessage() {}

func (x *ConfigMutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMutationRequest.ProtoReflect.Descriptor instead.
func (*ConfigMutationRequest) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigMutationRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigMutationRequest) GetValue() *ProtoconfValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigMutationRequest) GetScriptMetadata() string {
	if x != nil {
		return x.ScriptMetadata
	}
	return ""
}

type ConfigMutationResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Uuid       string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CommitHash string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Links      map[string]string      `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Result:
	//
	//	*ConfigMutationResponse_Success
	//	*ConfigMutationResponse_Failure
	Result             isConfigMutationResponse_Result `protobuf_oneof:"result"`
	ErrorMessage       string                          `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PreScriptDuration  *durationpb.Duration            `protobuf:"bytes,7,opt,name=pre_script_duration,json=preScriptDuration,proto3" json:"pre_script_duration,omitempty"`
	PostScriptDuration *durationpb.Duration            `protobuf:"bytes,8,opt,name=post_script_duration,json=postScriptDuration,proto3" json:"post_script_duration,omitempty"`
	CompileDuration    *durationpb.Duration            `protobuf:"bytes,9,opt,name=compile_duration,json=compileDuration,proto3" json:"compile_duration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigMutationResponse) Reset() {
	*x = ConfigMutationResponse{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMutationResponse) ProtoMessage() {}

func (x *ConfigMutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMutationResponse.ProtoReflect.Descriptor instead.
func (*ConfigMutationResponse) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigMutationResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ConfigMutationResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ConfigMutationResponse) GetLinks() map[string]string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ConfigMutationResponse) GetResult() isConfigMutationResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ConfigMutationResponse) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Result.(*ConfigMutationResponse_Success); ok {
			return x.Success
		}
	}
	return false
}

func (x *ConfigMutationResponse) GetFailure() bool {
	if x != nil {
		if x, ok := x.Result.(*ConfigMutationResponse_Failure); ok {
			return x.Failure
		}
	}
	return false
}

func (x *ConfigMutationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConfigMutationResponse) GetPreScriptDuration() *durationpb.Duration {
	if x != nil {
		return x.PreScriptDuration
	}
	return nil
}

func (x *ConfigMutationResponse) GetPostScriptDuration() *durationpb.Duration {
	if x != nil {
		return x.PostScriptDuration
	}
	return nil
}

func (x *ConfigMutationResponse) GetCompileDuration() *durationpb.Duration {
	if x != nil {
		return x.CompileDuration
	}
	return nil
}

type isConfigMutationResponse_Result interface {
	isConfigMutationResponse_Result()
}

type ConfigMutationResponse_Success struct {
	Success bool `protobuf:"varint,4,opt,name=success,proto3,oneof"`
}

type ConfigMutationResponse_Failure struct {
	Failure bool `protobuf:"varint,5,opt,name=failure,proto3,oneof"`
}

func (*ConfigMutationResponse_Success) isConfigMutationResponse_Result() {}

func (*ConfigMutationResponse_Failure) isConfigMutationResponse_Result() {}

// Compiler
type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	SkipDisk      bool                   `protobuf:"varint,2,opt,name=skip_disk,json=skipDisk,proto3" json:"skip_disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{7}
}

func (x *CompileRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *CompileRequest) GetSkipDisk() bool {
	if x != nil {
		return x.SkipDisk
	}
	return false
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Result        *ProtoconfValue        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{8}
}

func (x *CompileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CompileResponse) GetResult() *ProtoconfValue {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompileResponse) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *CompileResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ProtoconfValue_ConfigRollout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cooldown is the duration of time the inserter waits before applying
	// the next stage, Uses protobuf google.protobuf.Duration well-known-type
	DefaultCooldownTime *durationpb.Duration `protobuf:"bytes,1,opt,name=default_cooldown_time,json=defaultCooldownTime,proto3" json:"default_cooldown_time,omitempty"`
	// expiration will be added to the time of insertion to be set as
	// `expires_at`. When `expires_at` is due, the config should revert
	// to default.
	DefaultExpirationTime *durationpb.Duration                  `protobuf:"bytes,2,opt,name=default_expiration_time,json=defaultExpirationTime,proto3" json:"default_expiration_time,omitempty"`
	Stages                []*ProtoconfValue_ConfigRollout_Stage `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	Namespace             string                                `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProtoconfValue_ConfigRollout) Reset() {
	*x = ProtoconfValue_ConfigRollout{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoconfValue_ConfigRollout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoconfValue_ConfigRollout) ProtoMessage() {}

func (x *ProtoconfValue_ConfigRollout) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoconfValue_ConfigRollout.ProtoReflect.Descriptor instead.
func (*ProtoconfValue_ConfigRollout) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProtoconfValue_ConfigRollout) GetDefaultCooldownTime() *durationpb.Duration {
	if x != nil {
		return x.DefaultCooldownTime
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout) GetDefaultExpirationTime() *durationpb.Duration {
	if x != nil {
		return x.DefaultExpirationTime
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout) GetStages() []*ProtoconfValue_ConfigRollout_Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ProtoconfValue_ConfigRollout_Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Percentile    uint32                 `protobuf:"varint,2,opt,name=percentile,proto3" json:"percentile,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Manual        bool                   `protobuf:"varint,4,opt,name=manual,proto3" json:"manual,omitempty"`
	Cooldown      *durationpb.Duration   `protobuf:"bytes,5,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	Expiration    *durationpb.Duration   `protobuf:"bytes,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoconfValue_ConfigRollout_Stage) Reset() {
	*x = ProtoconfValue_ConfigRollout_Stage{}
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoconfValue_ConfigRollout_Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoconfValue_ConfigRollout_Stage) ProtoMessage() {}

func (x *ProtoconfValue_ConfigRollout_Stage) ProtoReflect() protoreflect.Message {
	mi := &file_protoconf_v1_protoconf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoconfValue_ConfigRollout_Stage.ProtoReflect.Descriptor instead.
func (*ProtoconfValue_ConfigRollout_Stage) Descriptor() ([]byte, []int) {
	return file_protoconf_v1_protoconf_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetPercentile() uint32 {
	if x != nil {
		return x.Percentile
	}
	return 0
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetManual() bool {
	if x != nil {
		return x.Manual
	}
	return false
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetCooldown() *durationpb.Duration {
	if x != nil {
		return x.Cooldown
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetExpiration() *durationpb.Duration {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_protoconf_v1_protoconf_proto protoreflect.FileDescriptor

const file_protoconf_v1_protoconf_proto_rawDesc = "" +
	"\n" +
	"\x1cprotoconf/v1/protoconf.proto\x12\fprotoconf.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/api/httpbody.proto\"\xb2\a\n" +
	"\x0eProtoconfValue\x12\x1d\n" +
	"\n" +
	"proto_file\x18\x01 \x01(\tR\tprotoFile\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12Q\n" +
	"\x0erollout_config\x18\x03 \x01(\v2*.protoconf.v1.ProtoconfValue.ConfigRolloutR\rrolloutConfig\x122\n" +
	"\bmetadata\x18\x04 \x01(\v2\x16.protoconf.v1.MetadataR\bmetadata\x1a\xcd\x05\n" +
	"\rConfigRollout\x12M\n" +
	"\x15default_cooldown_time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x13defaultCooldownTime\x12Q\n" +
	"\x17default_expiration_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x15defaultExpirationTime\x12H\n" +
	"\x06stages\x18\x03 \x03(\v20.protoconf.v1.ProtoconfValue.ConfigRollout.StageR\x06stages\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x1a\xb1\x03\n" +
	"\x05Stage\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1e\n" +
	"\n" +
	"percentile\x18\x02 \x01(\rR\n" +
	"percentile\x12T\n" +
	"\x06labels\x18\x03 \x03(\v2<.protoconf.v1.ProtoconfValue.ConfigRollout.Stage.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06manual\x18\x04 \x01(\bR\x06manual\x125\n" +
	"\bcooldown\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bcooldown\x129\n" +
	"\n" +
	"expiration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"expiration\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\bMetadata\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\x12'\n" +
	"\x0fcommitter_email\x18\x02 \x01(\tR\x0ecommitterEmail\x12!\n" +
	"\fauthor_email\x18\x03 \x01(\tR\vauthorEmail\x12=\n" +
	"\fcommitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\x12;\n" +
	"\vauthored_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"authoredAt\x12;\n" +
	"\vinserted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"insertedAt\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\"I\n" +
	"\x19ConfigSubscriptionRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"=\n" +
	"\rConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"x\n" +
	"\fConfigUpdate\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\x03raw\x18\x03 \x01(\v2\x14.google.api.HttpBodyR\x03raw\"\x88\x01\n" +
	"\x15ConfigMutationRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.protoconf.v1.ProtoconfValueR\x05value\x12'\n" +
	"\x0fscript_metadata\x18\x03 \x01(\tR\x0escriptMetadata\"\x93\x04\n" +
	"\x16ConfigMutationResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12E\n" +
	"\x05links\x18\x03 \x03(\v2/.protoconf.v1.ConfigMutationResponse.LinksEntryR\x05links\x12\x1a\n" +
	"\asuccess\x18\x04 \x01(\bH\x00R\asuccess\x12\x1a\n" +
	"\afailure\x18\x05 \x01(\bH\x00R\afailure\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12I\n" +
	"\x13pre_script_duration\x18\a \x01(\v2\x19.google.protobuf.DurationR\x11preScriptDuration\x12K\n" +
	"\x14post_script_duration\x18\b \x01(\v2\x19.google.protobuf.DurationR\x12postScriptDuration\x12D\n" +
	"\x10compile_duration\x18\t \x01(\v2\x19.google.protobuf.DurationR\x0fcompileDuration\x1a8\n" +
	"\n" +
	"LinksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06result\"C\n" +
	"\x0eCompileRequest\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x12\x1b\n" +
	"\tskip_disk\x18\x02 \x01(\bR\bskipDisk\"\x87\x01\n" +
	"\x0fCompileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.protoconf.v1.ProtoconfValueR\x06result\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors2\xb5\x01\n" +
	"\x10ProtoconfService\x12[\n" +
	"\x12SubscribeForConfig\x12'.protoconf.v1.ConfigSubscriptionRequest\x1a\x1a.protoconf.v1.ConfigUpdate0\x01\x12D\n" +
	"\tGetConfig\x12\x1b.protoconf.v1.ConfigRequest\x1a\x1a.protoconf.v1.ConfigUpdate2u\n" +
	"\x18ProtoconfMutationService\x12Y\n" +
	"\fMutateConfig\x12#.protoconf.v1.ConfigMutationRequest\x1a$.protoconf.v1.ConfigMutationResponse2~\n" +
	"\x1eProtoconfMutationReportService\x12\\\n" +
	"\x0eReportProgress\x12$.protoconf.v1.ConfigMutationResponse\x1a$.protoconf.v1.ConfigMutationResponse2a\n" +
	"\x10ProtoconfCompile\x12M\n" +
	"\fCompileFiles\x12\x1c.protoconf.v1.CompileRequest\x1a\x1d.protoconf.v1.CompileResponse0\x01BY\n" +
	"\x1acom.protoconf.datatypes.v1Z;github.com/protoconf/protoconf/pb/protoconf/v1;protoconf_pbb\x06proto3"

var (
	file_protoconf_v1_protoconf_proto_rawDescOnce sync.Once
	file_protoconf_v1_protoconf_proto_rawDescData []byte
)

func file_protoconf_v1_protoconf_proto_rawDescGZIP() []byte {
	file_protoconf_v1_protoconf_proto_rawDescOnce.Do(func() {
		file_protoconf_v1_protoconf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoconf_v1_protoconf_proto_rawDesc), len(file_protoconf_v1_protoconf_proto_rawDesc)))
	})
	return file_protoconf_v1_protoconf_proto_rawDescData
}

var file_protoconf_v1_protoconf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protoconf_v1_protoconf_proto_goTypes = []any{
	(*ProtoconfValue)(nil),                     // 0: protoconf.v1.ProtoconfValue
	(*Metadata)(nil),                           // 1: protoconf.v1.Metadata
	(*ConfigSubscriptionRequest)(nil),          // 2: protoconf.v1.ConfigSubscriptionRequest
	(*ConfigRequest)(nil),                      // 3: protoconf.v1.ConfigRequest
	(*ConfigUpdate)(nil),                       // 4: protoconf.v1.ConfigUpdate
	(*ConfigMutationRequest)(nil),              // 5: protoconf.v1.ConfigMutationRequest
	(*ConfigMutationResponse)(nil),             // 6: protoconf.v1.ConfigMutationResponse
	(*CompileRequest)(nil),                     // 7: protoconf.v1.CompileRequest
	(*CompileResponse)(nil),                    // 8: protoconf.v1.CompileResponse
	(*ProtoconfValue_ConfigRollout)(nil),       // 9: protoconf.v1.ProtoconfValue.ConfigRollout
	(*ProtoconfValue_ConfigRollout_Stage)(nil), // 10: protoconf.v1.ProtoconfValue.ConfigRollout.Stage
	nil,                           // 11: protoconf.v1.ProtoconfValue.ConfigRollout.Stage.LabelsEntry
	nil,                           // 12: protoconf.v1.ConfigMutationResponse.LinksEntry
	(*anypb.Any)(nil),             // 13: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*httpbody.HttpBody)(nil),     // 15: google.api.HttpBody
	(*durationpb.Duration)(nil),   // 16: google.protobuf.Duration
}
var file_protoconf_v1_protoconf_proto_depIdxs = []int32{
	13, // 0: protoconf.v1.ProtoconfValue.value:type_name -> google.protobuf.Any
	9,  // 1: protoconf.v1.ProtoconfValue.rollout_config:type_name -> protoconf.v1.ProtoconfValue.ConfigRollout
	1,  // 2: protoconf.v1.ProtoconfValue.metadata:type_name -> protoconf.v1.Metadata
	14, // 3: protoconf.v1.Metadata.committed_at:type_name -> google.protobuf.Timestamp
	14, // 4: protoconf.v1.Metadata.authored_at:type_name -> google.protobuf.Timestamp
	14, // 5: protoconf.v1.Metadata.inserted_at:type_name -> google.protobuf.Timestamp
	13, // 6: protoconf.v1.ConfigUpdate.value:type_name -> google.protobuf.Any
	15, // 7: protoconf.v1.ConfigUpdate.raw:type_name -> google.api.HttpBody
	0,  // 8: protoconf.v1.ConfigMutationRequest.value:type_name -> protoconf.v1.ProtoconfValue
	12, // 9: protoconf.v1.ConfigMutationResponse.links:type_name -> protoconf.v1.ConfigMutationResponse.LinksEntry
	16, // 10: protoconf.v1.ConfigMutationResponse.pre_script_duration:type_name -> google.protobuf.Duration
	16, // 11: protoconf.v1.ConfigMutationResponse.post_script_duration:type_name -> google.protobuf.Duration
	16, // 12: protoconf.v1.ConfigMutationResponse.compile_duration:type_name -> google.protobuf.Duration
	0,  // 13: protoconf.v1.CompileResponse.result:type_name -> protoconf.v1.ProtoconfValue
	16, // 14: protoconf.v1.ProtoconfValue.ConfigRollout.default_cooldown_time:type_name -> google.protobuf.Duration
	16, // 15: protoconf.v1.ProtoconfValue.ConfigRollout.default_expiration_time:type_name -> google.protobuf.Duration
	10, // 16: protoconf.v1.ProtoconfValue.ConfigRollout.stages:type_name -> protoconf.v1.ProtoconfValue.ConfigRollout.Stage
	11, // 17: protoconf.v1.ProtoconfValue.ConfigRollout.Stage.labels:type_name -> protoconf.v1.ProtoconfValue.ConfigRollout.Stage.LabelsEntry
	16, // 18: protoconf.v1.ProtoconfValue.ConfigRollout.Stage.cooldown:type_name -> google.protobuf.Duration
	16, // 19: protoconf.v1.ProtoconfValue.ConfigRollout.Stage.expiration:type_name -> google.protobuf.Duration
	14, // 20: protoconf.v1.ProtoconfValue.ConfigRollout.Stage.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 21: protoconf.v1.ProtoconfService.SubscribeForConfig:input_type -> protoconf.v1.ConfigSubscriptionRequest
	3,  // 22: protoconf.v1.ProtoconfService.GetConfig:input_type -> protoconf.v1.ConfigRequest
	5,  // 23: protoconf.v1.ProtoconfMutationService.MutateConfig:input_type -> protoconf.v1.ConfigMutationRequest
	6,  // 24: protoconf.v1.ProtoconfMutationReportService.ReportProgress:input_type -> protoconf.v1.ConfigMutationResponse
	7,  // 25: protoconf.v1.ProtoconfCompile.CompileFiles:input_type -> protoconf.v1.CompileRequest
	4,  // 26: protoconf.v1.ProtoconfService.SubscribeForConfig:output_type -> protoconf.v1.ConfigUpdate
	4,  // 27: protoconf.v1.ProtoconfService.GetConfig:output_type -> protoconf.v1.ConfigUpdate
	6,  // 28: protoconf.v1.ProtoconfMutationService.MutateConfig:output_type -> protoconf.v1.ConfigMutationResponse
	6,  // 29: protoconf.v1.ProtoconfMutationReportService.ReportProgress:output_type -> protoconf.v1.ConfigMutationResponse
	8,  // 30: protoconf.v1.ProtoconfCompile.CompileFiles:output_type -> protoconf.v1.CompileResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_protoconf_v1_protoconf_proto_init() }
func file_protoconf_v1_protoconf_proto_init() {
	if File_protoconf_v1_protoconf_proto != nil {
		return
	}
	file_protoconf_v1_protoconf_proto_msgTypes[6].OneofWrappers = []any{
		(*ConfigMutationResponse_Success)(nil),
		(*ConfigMutationResponse_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoconf_v1_protoconf_proto_rawDesc), len(file_protoconf_v1_protoconf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_protoconf_v1_protoconf_proto_goTypes,
		DependencyIndexes: file_protoconf_v1_protoconf_proto_depIdxs,
		MessageInfos:      file_protoconf_v1_protoconf_proto_msgTypes,
	}.Build()
	File_protoconf_v1_protoconf_proto = out.File
	file_protoconf_v1_protoconf_proto_goTypes = nil
	file_protoconf_v1_protoconf_proto_depIdxs = nil
}
