site_name: protoconf
site_url: https://protoconf.github.io/protoconf
theme:
  favicon: assets/images/favicon.ico
  logo: assets/protoconf_new.svg
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate 
    primary: white 
    accent: yellow
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: yellow
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
repo_url: https://github.com/protoconf/protoconf
repo_name: protoconf/protoconf
markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
google_analytics:
  - G-H3NLBNNQD7
  - auto
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Structure Your Code: structuring-your-code.md
  - Multiple Outputs: multiple-outputs.md
  - Protoconf Exec: protoconf-exec.md
  - Mutation RPC: mutation-rpc.md
  - Integrations:
    - Terraform: integrations/terraform.md
    - Terraform Kubernetes: integrations/terraform_kubernetes.md
