// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: server/config/v1/server_config.proto

package protoconf_server_config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerConfig defines the configuration for the protoconf mutation server.
type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC address to bind to. For example: "0.0.0.0:4301"
	GrpcAddress string `protobuf:"bytes,1,opt,name=grpc_address,json=grpc-address,proto3" json:"grpc_address,omitempty"`
	// Pre-mutation script to run before applying a mutation.
	PreMutationScript string `protobuf:"bytes,2,opt,name=pre_mutation_script,json=pre,proto3" json:"pre_mutation_script,omitempty"`
	// Post-mutation script to run after applying a mutation.
	PostMutationScript string `protobuf:"bytes,3,opt,name=post_mutation_script,json=post,proto3" json:"post_mutation_script,omitempty"`
	// TLS certificate file path.
	TlsCert string `protobuf:"bytes,4,opt,name=tls_cert,json=tls-cert,proto3" json:"tls_cert,omitempty"`
	// TLS key file path.
	TlsKey string `protobuf:"bytes,5,opt,name=tls_key,json=tls-key,proto3" json:"tls_key,omitempty"`
	// TLS CA certificate file path (enables client cert verification).
	TlsCa string `protobuf:"bytes,6,opt,name=tls_ca,json=tls-ca,proto3" json:"tls_ca,omitempty"`
	// Bearer token for mutation authentication (if empty, auth is disabled).
	AuthToken string `protobuf:"bytes,7,opt,name=auth_token,json=auth-token,proto3" json:"auth_token,omitempty"`
	// Enables OpenTelemetry trace and metric export over OTLP/gRPC. Off by
	// default -- no collector is contacted when this is unset.
	EnableOtel    bool `protobuf:"varint,8,opt,name=enable_otel,json=enable-otel,proto3" json:"enable_otel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_server_config_v1_server_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_server_config_v1_server_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_server_config_v1_server_config_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *ServerConfig) GetPreMutationScript() string {
	if x != nil {
		return x.PreMutationScript
	}
	return ""
}

func (x *ServerConfig) GetPostMutationScript() string {
	if x != nil {
		return x.PostMutationScript
	}
	return ""
}

func (x *ServerConfig) GetTlsCert() string {
	if x != nil {
		return x.TlsCert
	}
	return ""
}

func (x *ServerConfig) GetTlsKey() string {
	if x != nil {
		return x.TlsKey
	}
	return ""
}

func (x *ServerConfig) GetTlsCa() string {
	if x != nil {
		return x.TlsCa
	}
	return ""
}

func (x *ServerConfig) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *ServerConfig) GetEnableOtel() bool {
	if x != nil {
		return x.EnableOtel
	}
	return false
}

var File_server_config_v1_server_config_proto protoreflect.FileDescriptor

const file_server_config_v1_server_config_proto_rawDesc = "" +
	"\n" +
	"$server/config/v1/server_config.proto\x12\x1aprotoconf.server.config.v1\"\x88\x02\n" +
	"\fServerConfig\x12\"\n" +
	"\fgrpc_address\x18\x01 \x01(\tR\fgrpc-address\x12 \n" +
	"\x13pre_mutation_script\x18\x02 \x01(\tR\x03pre\x12\"\n" +
	"\x14post_mutation_script\x18\x03 \x01(\tR\x04post\x12\x1a\n" +
	"\btls_cert\x18\x04 \x01(\tR\btls-cert\x12\x18\n" +
	"\atls_key\x18\x05 \x01(\tR\atls-key\x12\x16\n" +
	"\x06tls_ca\x18\x06 \x01(\tR\x06tls-ca\x12\x1e\n" +
	"\n" +
	"auth_token\x18\a \x01(\tR\n" +
	"auth-token\x12 \n" +
	"\venable_otel\x18\b \x01(\bR\venable-otelBIZGgithub.com/protoconf/protoconf/server/config/v1;protoconf_server_configb\x06proto3"

var (
	file_server_config_v1_server_config_proto_rawDescOnce sync.Once
	file_server_config_v1_server_config_proto_rawDescData []byte
)

func file_server_config_v1_server_config_proto_rawDescGZIP() []byte {
	file_server_config_v1_server_config_proto_rawDescOnce.Do(func() {
		file_server_config_v1_server_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_config_v1_server_config_proto_rawDesc), len(file_server_config_v1_server_config_proto_rawDesc)))
	})
	return file_server_config_v1_server_config_proto_rawDescData
}

var file_server_config_v1_server_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_config_v1_server_config_proto_goTypes = []any{
	(*ServerConfig)(nil), // 0: protoconf.server.config.v1.ServerConfig
}
var file_server_config_v1_server_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_config_v1_server_config_proto_init() }
func file_server_config_v1_server_config_proto_init() {
	if File_server_config_v1_server_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_config_v1_server_config_proto_rawDesc), len(file_server_config_v1_server_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_config_v1_server_config_proto_goTypes,
		DependencyIndexes: file_server_config_v1_server_config_proto_depIdxs,
		MessageInfos:      file_server_config_v1_server_config_proto_msgTypes,
	}.Build()
	File_server_config_v1_server_config_proto = out.File
	file_server_config_v1_server_config_proto_goTypes = nil
	file_server_config_v1_server_config_proto_depIdxs = nil
}
