# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: server/api/proto/v1/protoconf_mutation.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import datatypes.proto.v1.protoconf_value_pb2
import server.api.proto.v1.protoconf_mutation_pb2


class ProtoconfMutationServiceBase(abc.ABC):

    @abc.abstractmethod
    async def MutateConfig(self, stream: 'grpclib.server.Stream[server.api.proto.v1.protoconf_mutation_pb2.ConfigMutationRequest, server.api.proto.v1.protoconf_mutation_pb2.ConfigMutationResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/v1.ProtoconfMutationService/MutateConfig': grpclib.const.Handler(
                self.MutateConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                server.api.proto.v1.protoconf_mutation_pb2.ConfigMutationRequest,
                server.api.proto.v1.protoconf_mutation_pb2.ConfigMutationResponse,
            ),
        }


class ProtoconfMutationServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.MutateConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            '/v1.ProtoconfMutationService/MutateConfig',
            server.api.proto.v1.protoconf_mutation_pb2.ConfigMutationRequest,
            server.api.proto.v1.protoconf_mutation_pb2.ConfigMutationResponse,
        )
