// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: agent/config/v1/agent_config.proto

package protoconf_agent_config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentConfig_StoreType int32

const (
	AgentConfig_consul     AgentConfig_StoreType = 0
	AgentConfig_etcd       AgentConfig_StoreType = 1
	AgentConfig_zookeeper  AgentConfig_StoreType = 2
	AgentConfig_file       AgentConfig_StoreType = 3
	AgentConfig_configmaps AgentConfig_StoreType = 4
)

// Enum value maps for AgentConfig_StoreType.
var (
	AgentConfig_StoreType_name = map[int32]string{
		0: "consul",
		1: "etcd",
		2: "zookeeper",
		3: "file",
		4: "configmaps",
	}
	AgentConfig_StoreType_value = map[string]int32{
		"consul":     0,
		"etcd":       1,
		"zookeeper":  2,
		"file":       3,
		"configmaps": 4,
	}
)

func (x AgentConfig_StoreType) Enum() *AgentConfig_StoreType {
	p := new(AgentConfig_StoreType)
	*p = x
	return p
}

func (x AgentConfig_StoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentConfig_StoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_config_v1_agent_config_proto_enumTypes[0].Descriptor()
}

func (AgentConfig_StoreType) Type() protoreflect.EnumType {
	return &file_agent_config_v1_agent_config_proto_enumTypes[0]
}

func (x AgentConfig_StoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentConfig_StoreType.Descriptor instead.
func (AgentConfig_StoreType) EnumDescriptor() ([]byte, []int) {
	return file_agent_config_v1_agent_config_proto_rawDescGZIP(), []int{0, 0}
}

type AgentConfig_LogLevel int32

const (
	AgentConfig_INFO  AgentConfig_LogLevel = 0
	AgentConfig_DEBUG AgentConfig_LogLevel = -4
	AgentConfig_WARN  AgentConfig_LogLevel = 4
	AgentConfig_ERROR AgentConfig_LogLevel = 8
)

// Enum value maps for AgentConfig_LogLevel.
var (
	AgentConfig_LogLevel_name = map[int32]string{
		0:  "INFO",
		-4: "DEBUG",
		4:  "WARN",
		8:  "ERROR",
	}
	AgentConfig_LogLevel_value = map[string]int32{
		"INFO":  0,
		"DEBUG": -4,
		"WARN":  4,
		"ERROR": 8,
	}
)

func (x AgentConfig_LogLevel) Enum() *AgentConfig_LogLevel {
	p := new(AgentConfig_LogLevel)
	*p = x
	return p
}

func (x AgentConfig_LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentConfig_LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_config_v1_agent_config_proto_enumTypes[1].Descriptor()
}

func (AgentConfig_LogLevel) Type() protoreflect.EnumType {
	return &file_agent_config_v1_agent_config_proto_enumTypes[1]
}

func (x AgentConfig_LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentConfig_LogLevel.Descriptor instead.
func (AgentConfig_LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_agent_config_v1_agent_config_proto_rawDescGZIP(), []int{0, 1}
}

// Protoconf agent configuration guide.
type AgentConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configures the address which the gRPC server will bind to.
	// For example: "0.0.0.0:4300"
	GrpcAddress string `protobuf:"bytes,1,opt,name=grpc_address,json=grpc-address,proto3" json:"grpc_address,omitempty"`
	// Configures the address which the HTTP admin server will bind to.
	// For example: "0.0.0.0:4390"
	// This admin server return metrics under `/metrics`
	HttpAddress   string                 `protobuf:"bytes,2,opt,name=http_address,json=http-address,proto3" json:"http_address,omitempty"`
	DevRoot       string                 `protobuf:"bytes,3,opt,name=dev_root,json=dev,proto3" json:"dev_root,omitempty"`
	Store         AgentConfig_StoreType  `protobuf:"varint,4,opt,name=store,proto3,enum=protoconf.agent.config.v1.AgentConfig_StoreType" json:"store,omitempty"`
	Servers       []string               `protobuf:"bytes,5,rep,name=servers,json=store-address,proto3" json:"servers,omitempty"`
	Prefix        string                 `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Insecure      bool                   `protobuf:"varint,7,opt,name=insecure,proto3" json:"insecure,omitempty"`
	TlsConfig     *AgentConfig_TLSConfig `protobuf:"bytes,8,opt,name=tls_config,json=tls-config,proto3" json:"tls_config,omitempty"`
	StoreTls      *AgentConfig_TLSConfig `protobuf:"bytes,9,opt,name=store_tls,json=store-tls,proto3" json:"store_tls,omitempty"`
	LogAsJson     bool                   `protobuf:"varint,10,opt,name=log_as_json,json=log-as-json,proto3" json:"log_as_json,omitempty"`
	LogLevel      AgentConfig_LogLevel   `protobuf:"varint,11,opt,name=log_level,json=log-level,proto3,enum=protoconf.agent.config.v1.AgentConfig_LogLevel" json:"log_level,omitempty"`
	LogSource     bool                   `protobuf:"varint,12,opt,name=log_source,json=log-source,proto3" json:"log_source,omitempty"`
	ChannelName   string                 `protobuf:"bytes,13,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,14,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,15,opt,name=namespace,proto3" json:"namespace,omitempty"`
	EnableRollout bool                   `protobuf:"varint,16,opt,name=enable_rollout,json=enable-rollout,proto3" json:"enable_rollout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_agent_config_v1_agent_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_v1_agent_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_agent_config_v1_agent_config_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConfig) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *AgentConfig) GetHttpAddress() string {
	if x != nil {
		return x.HttpAddress
	}
	return ""
}

func (x *AgentConfig) GetDevRoot() string {
	if x != nil {
		return x.DevRoot
	}
	return ""
}

func (x *AgentConfig) GetStore() AgentConfig_StoreType {
	if x != nil {
		return x.Store
	}
	return AgentConfig_consul
}

func (x *AgentConfig) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *AgentConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AgentConfig) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *AgentConfig) GetTlsConfig() *AgentConfig_TLSConfig {
	if x != nil {
		return x.TlsConfig
	}
	return nil
}

func (x *AgentConfig) GetStoreTls() *AgentConfig_TLSConfig {
	if x != nil {
		return x.StoreTls
	}
	return nil
}

func (x *AgentConfig) GetLogAsJson() bool {
	if x != nil {
		return x.LogAsJson
	}
	return false
}

func (x *AgentConfig) GetLogLevel() AgentConfig_LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return AgentConfig_INFO
}

func (x *AgentConfig) GetLogSource() bool {
	if x != nil {
		return x.LogSource
	}
	return false
}

func (x *AgentConfig) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *AgentConfig) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AgentConfig) GetEnableRollout() bool {
	if x != nil {
		return x.EnableRollout
	}
	return false
}

type AgentConfig_TLSConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*AgentConfig_TLSConfig_KeyText
	//	*AgentConfig_TLSConfig_KeyFile
	Key isAgentConfig_TLSConfig_Key `protobuf_oneof:"key"`
	// Types that are valid to be assigned to Cert:
	//
	//	*AgentConfig_TLSConfig_CertText
	//	*AgentConfig_TLSConfig_CertFile
	Cert isAgentConfig_TLSConfig_Cert `protobuf_oneof:"cert"`
	// Types that are valid to be assigned to Ca:
	//
	//	*AgentConfig_TLSConfig_CaText
	//	*AgentConfig_TLSConfig_CaFile
	Ca            isAgentConfig_TLSConfig_Ca `protobuf_oneof:"ca"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig_TLSConfig) Reset() {
	*x = AgentConfig_TLSConfig{}
	mi := &file_agent_config_v1_agent_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig_TLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig_TLSConfig) ProtoMessage() {}

func (x *AgentConfig_TLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_v1_agent_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig_TLSConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig_TLSConfig) Descriptor() ([]byte, []int) {
	return file_agent_config_v1_agent_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AgentConfig_TLSConfig) GetKey() isAgentConfig_TLSConfig_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AgentConfig_TLSConfig) GetKeyText() string {
	if x != nil {
		if x, ok := x.Key.(*AgentConfig_TLSConfig_KeyText); ok {
			return x.KeyText
		}
	}
	return ""
}

func (x *AgentConfig_TLSConfig) GetKeyFile() string {
	if x != nil {
		if x, ok := x.Key.(*AgentConfig_TLSConfig_KeyFile); ok {
			return x.KeyFile
		}
	}
	return ""
}

func (x *AgentConfig_TLSConfig) GetCert() isAgentConfig_TLSConfig_Cert {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *AgentConfig_TLSConfig) GetCertText() string {
	if x != nil {
		if x, ok := x.Cert.(*AgentConfig_TLSConfig_CertText); ok {
			return x.CertText
		}
	}
	return ""
}

func (x *AgentConfig_TLSConfig) GetCertFile() string {
	if x != nil {
		if x, ok := x.Cert.(*AgentConfig_TLSConfig_CertFile); ok {
			return x.CertFile
		}
	}
	return ""
}

func (x *AgentConfig_TLSConfig) GetCa() isAgentConfig_TLSConfig_Ca {
	if x != nil {
		return x.Ca
	}
	return nil
}

func (x *AgentConfig_TLSConfig) GetCaText() string {
	if x != nil {
		if x, ok := x.Ca.(*AgentConfig_TLSConfig_CaText); ok {
			return x.CaText
		}
	}
	return ""
}

func (x *AgentConfig_TLSConfig) GetCaFile() string {
	if x != nil {
		if x, ok := x.Ca.(*AgentConfig_TLSConfig_CaFile); ok {
			return x.CaFile
		}
	}
	return ""
}

type isAgentConfig_TLSConfig_Key interface {
	isAgentConfig_TLSConfig_Key()
}

type AgentConfig_TLSConfig_KeyText struct {
	KeyText string `protobuf:"bytes,1,opt,name=key_text,json=key-text,proto3,oneof"`
}

type AgentConfig_TLSConfig_KeyFile struct {
	KeyFile string `protobuf:"bytes,2,opt,name=key_file,json=key-file,proto3,oneof"`
}

func (*AgentConfig_TLSConfig_KeyText) isAgentConfig_TLSConfig_Key() {}

func (*AgentConfig_TLSConfig_KeyFile) isAgentConfig_TLSConfig_Key() {}

type isAgentConfig_TLSConfig_Cert interface {
	isAgentConfig_TLSConfig_Cert()
}

type AgentConfig_TLSConfig_CertText struct {
	CertText string `protobuf:"bytes,3,opt,name=cert_text,json=cert-text,proto3,oneof"`
}

type AgentConfig_TLSConfig_CertFile struct {
	CertFile string `protobuf:"bytes,4,opt,name=cert_file,json=cert-file,proto3,oneof"`
}

func (*AgentConfig_TLSConfig_CertText) isAgentConfig_TLSConfig_Cert() {}

func (*AgentConfig_TLSConfig_CertFile) isAgentConfig_TLSConfig_Cert() {}

type isAgentConfig_TLSConfig_Ca interface {
	isAgentConfig_TLSConfig_Ca()
}

type AgentConfig_TLSConfig_CaText struct {
	CaText string `protobuf:"bytes,5,opt,name=ca_text,json=ca-text,proto3,oneof"`
}

type AgentConfig_TLSConfig_CaFile struct {
	CaFile string `protobuf:"bytes,6,opt,name=ca_file,json=ca-file,proto3,oneof"`
}

func (*AgentConfig_TLSConfig_CaText) isAgentConfig_TLSConfig_Ca() {}

func (*AgentConfig_TLSConfig_CaFile) isAgentConfig_TLSConfig_Ca() {}

var File_agent_config_v1_agent_config_proto protoreflect.FileDescriptor

const file_agent_config_v1_agent_config_proto_rawDesc = "" +
	"\n" +
	"\"agent/config/v1/agent_config.proto\x12\x19protoconf.agent.config.v1\"\xa1\b\n" +
	"\vAgentConfig\x12\"\n" +
	"\fgrpc_address\x18\x01 \x01(\tR\fgrpc-address\x12\"\n" +
	"\fhttp_address\x18\x02 \x01(\tR\fhttp-address\x12\x15\n" +
	"\bdev_root\x18\x03 \x01(\tR\x03dev\x12F\n" +
	"\x05store\x18\x04 \x01(\x0e20.protoconf.agent.config.v1.AgentConfig.StoreTypeR\x05store\x12\x1e\n" +
	"\aservers\x18\x05 \x03(\tR\rstore-address\x12\x16\n" +
	"\x06prefix\x18\x06 \x01(\tR\x06prefix\x12\x1a\n" +
	"\binsecure\x18\a \x01(\bR\binsecure\x12P\n" +
	"\n" +
	"tls_config\x18\b \x01(\v20.protoconf.agent.config.v1.AgentConfig.TLSConfigR\n" +
	"tls-config\x12N\n" +
	"\tstore_tls\x18\t \x01(\v20.protoconf.agent.config.v1.AgentConfig.TLSConfigR\tstore-tls\x12 \n" +
	"\vlog_as_json\x18\n" +
	" \x01(\bR\vlog-as-json\x12M\n" +
	"\tlog_level\x18\v \x01(\x0e2/.protoconf.agent.config.v1.AgentConfig.LogLevelR\tlog-level\x12\x1e\n" +
	"\n" +
	"log_source\x18\f \x01(\bR\n" +
	"log-source\x12!\n" +
	"\fchannel_name\x18\r \x01(\tR\vchannelName\x12\x19\n" +
	"\bagent_id\x18\x0e \x01(\tR\aagentId\x12\x1c\n" +
	"\tnamespace\x18\x0f \x01(\tR\tnamespace\x12&\n" +
	"\x0eenable_rollout\x18\x10 \x01(\bR\x0eenable-rollout\x1a\xd4\x01\n" +
	"\tTLSConfig\x12\x1c\n" +
	"\bkey_text\x18\x01 \x01(\tH\x00R\bkey-text\x12\x1c\n" +
	"\bkey_file\x18\x02 \x01(\tH\x00R\bkey-file\x12\x1e\n" +
	"\tcert_text\x18\x03 \x01(\tH\x01R\tcert-text\x12\x1e\n" +
	"\tcert_file\x18\x04 \x01(\tH\x01R\tcert-file\x12\x1a\n" +
	"\aca_text\x18\x05 \x01(\tH\x02R\aca-text\x12\x1a\n" +
	"\aca_file\x18\x06 \x01(\tH\x02R\aca-fileB\x05\n" +
	"\x03keyB\x06\n" +
	"\x04certB\x04\n" +
	"\x02ca\"J\n" +
	"\tStoreType\x12\n" +
	"\n" +
	"\x06consul\x10\x00\x12\b\n" +
	"\x04etcd\x10\x01\x12\r\n" +
	"\tzookeeper\x10\x02\x12\b\n" +
	"\x04file\x10\x03\x12\x0e\n" +
	"\n" +
	"configmaps\x10\x04\"=\n" +
	"\bLogLevel\x12\b\n" +
	"\x04INFO\x10\x00\x12\x12\n" +
	"\x05DEBUG\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\b\n" +
	"\x04WARN\x10\x04\x12\t\n" +
	"\x05ERROR\x10\bBGZEgithub.com/protoconf/protoconf/agent/config/v1;protoconf_agent_configb\x06proto3"

var (
	file_agent_config_v1_agent_config_proto_rawDescOnce sync.Once
	file_agent_config_v1_agent_config_proto_rawDescData []byte
)

func file_agent_config_v1_agent_config_proto_rawDescGZIP() []byte {
	file_agent_config_v1_agent_config_proto_rawDescOnce.Do(func() {
		file_agent_config_v1_agent_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_config_v1_agent_config_proto_rawDesc), len(file_agent_config_v1_agent_config_proto_rawDesc)))
	})
	return file_agent_config_v1_agent_config_proto_rawDescData
}

var file_agent_config_v1_agent_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_config_v1_agent_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_config_v1_agent_config_proto_goTypes = []any{
	(AgentConfig_StoreType)(0),    // 0: protoconf.agent.config.v1.AgentConfig.StoreType
	(AgentConfig_LogLevel)(0),     // 1: protoconf.agent.config.v1.AgentConfig.LogLevel
	(*AgentConfig)(nil),           // 2: protoconf.agent.config.v1.AgentConfig
	(*AgentConfig_TLSConfig)(nil), // 3: protoconf.agent.config.v1.AgentConfig.TLSConfig
}
var file_agent_config_v1_agent_config_proto_depIdxs = []int32{
	0, // 0: protoconf.agent.config.v1.AgentConfig.store:type_name -> protoconf.agent.config.v1.AgentConfig.StoreType
	3, // 1: protoconf.agent.config.v1.AgentConfig.tls_config:type_name -> protoconf.agent.config.v1.AgentConfig.TLSConfig
	3, // 2: protoconf.agent.config.v1.AgentConfig.store_tls:type_name -> protoconf.agent.config.v1.AgentConfig.TLSConfig
	1, // 3: protoconf.agent.config.v1.AgentConfig.log_level:type_name -> protoconf.agent.config.v1.AgentConfig.LogLevel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agent_config_v1_agent_config_proto_init() }
func file_agent_config_v1_agent_config_proto_init() {
	if File_agent_config_v1_agent_config_proto != nil {
		return
	}
	file_agent_config_v1_agent_config_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentConfig_TLSConfig_KeyText)(nil),
		(*AgentConfig_TLSConfig_KeyFile)(nil),
		(*AgentConfig_TLSConfig_CertText)(nil),
		(*AgentConfig_TLSConfig_CertFile)(nil),
		(*AgentConfig_TLSConfig_CaText)(nil),
		(*AgentConfig_TLSConfig_CaFile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_config_v1_agent_config_proto_rawDesc), len(file_agent_config_v1_agent_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_config_v1_agent_config_proto_goTypes,
		DependencyIndexes: file_agent_config_v1_agent_config_proto_depIdxs,
		EnumInfos:         file_agent_config_v1_agent_config_proto_enumTypes,
		MessageInfos:      file_agent_config_v1_agent_config_proto_msgTypes,
	}.Build()
	File_agent_config_v1_agent_config_proto = out.File
	file_agent_config_v1_agent_config_proto_goTypes = nil
	file_agent_config_v1_agent_config_proto_depIdxs = nil
}
