// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: datatypes/proto/v1/protoconf_value.proto

package datatypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoconfValue struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ProtoFile     string                        `protobuf:"bytes,1,opt,name=proto_file,json=protoFile,proto3" json:"proto_file,omitempty"`
	Value         *anypb.Any                    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RolloutConfig *ProtoconfValue_ConfigRollout `protobuf:"bytes,3,opt,name=rollout_config,json=rolloutConfig,proto3" json:"rollout_config,omitempty"`
	Metadata      *Metadata                     `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoconfValue) Reset() {
	*x = ProtoconfValue{}
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoconfValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoconfValue) ProtoMessage() {}

func (x *ProtoconfValue) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoconfValue.ProtoReflect.Descriptor instead.
func (*ProtoconfValue) Descriptor() ([]byte, []int) {
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoconfValue) GetProtoFile() string {
	if x != nil {
		return x.ProtoFile
	}
	return ""
}

func (x *ProtoconfValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProtoconfValue) GetRolloutConfig() *ProtoconfValue_ConfigRollout {
	if x != nil {
		return x.RolloutConfig
	}
	return nil
}

func (x *ProtoconfValue) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Commit         string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	CommitterEmail string                 `protobuf:"bytes,2,opt,name=committer_email,json=committerEmail,proto3" json:"committer_email,omitempty"`
	AuthorEmail    string                 `protobuf:"bytes,3,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	CommittedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	AuthoredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=authored_at,json=authoredAt,proto3" json:"authored_at,omitempty"`
	InsertedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=inserted_at,json=insertedAt,proto3" json:"inserted_at,omitempty"`
	Channel        string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Metadata) GetCommitterEmail() string {
	if x != nil {
		return x.CommitterEmail
	}
	return ""
}

func (x *Metadata) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Metadata) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

func (x *Metadata) GetAuthoredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthoredAt
	}
	return nil
}

func (x *Metadata) GetInsertedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InsertedAt
	}
	return nil
}

func (x *Metadata) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ProtoconfValue_ConfigRollout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cooldown is the duration of time the inserter waits before applying
	// the next stage, Uses protobuf google.protobuf.Duration well-known-type
	DefaultCooldownTime *durationpb.Duration `protobuf:"bytes,1,opt,name=default_cooldown_time,json=defaultCooldownTime,proto3" json:"default_cooldown_time,omitempty"`
	// expiration will be added to the time of insertion to be set as
	// `expires_at`. When `expires_at` is due, the config should revert
	// to default.
	DefaultExpirationTime *durationpb.Duration                  `protobuf:"bytes,2,opt,name=default_expiration_time,json=defaultExpirationTime,proto3" json:"default_expiration_time,omitempty"`
	Stages                []*ProtoconfValue_ConfigRollout_Stage `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	Namespace             string                                `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProtoconfValue_ConfigRollout) Reset() {
	*x = ProtoconfValue_ConfigRollout{}
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoconfValue_ConfigRollout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoconfValue_ConfigRollout) ProtoMessage() {}

func (x *ProtoconfValue_ConfigRollout) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoconfValue_ConfigRollout.ProtoReflect.Descriptor instead.
func (*ProtoconfValue_ConfigRollout) Descriptor() ([]byte, []int) {
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProtoconfValue_ConfigRollout) GetDefaultCooldownTime() *durationpb.Duration {
	if x != nil {
		return x.DefaultCooldownTime
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout) GetDefaultExpirationTime() *durationpb.Duration {
	if x != nil {
		return x.DefaultExpirationTime
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout) GetStages() []*ProtoconfValue_ConfigRollout_Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ProtoconfValue_ConfigRollout_Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Percentile    uint32                 `protobuf:"varint,2,opt,name=percentile,proto3" json:"percentile,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Manual        bool                   `protobuf:"varint,4,opt,name=manual,proto3" json:"manual,omitempty"`
	Cooldown      *durationpb.Duration   `protobuf:"bytes,5,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	Expiration    *durationpb.Duration   `protobuf:"bytes,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoconfValue_ConfigRollout_Stage) Reset() {
	*x = ProtoconfValue_ConfigRollout_Stage{}
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoconfValue_ConfigRollout_Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoconfValue_ConfigRollout_Stage) ProtoMessage() {}

func (x *ProtoconfValue_ConfigRollout_Stage) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoconfValue_ConfigRollout_Stage.ProtoReflect.Descriptor instead.
func (*ProtoconfValue_ConfigRollout_Stage) Descriptor() ([]byte, []int) {
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetPercentile() uint32 {
	if x != nil {
		return x.Percentile
	}
	return 0
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetManual() bool {
	if x != nil {
		return x.Manual
	}
	return false
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetCooldown() *durationpb.Duration {
	if x != nil {
		return x.Cooldown
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetExpiration() *durationpb.Duration {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ProtoconfValue_ConfigRollout_Stage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_datatypes_proto_v1_protoconf_value_proto protoreflect.FileDescriptor

const file_datatypes_proto_v1_protoconf_value_proto_rawDesc = "" +
	"\n" +
	"(datatypes/proto/v1/protoconf_value.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\a\n" +
	"\x0eProtoconfValue\x12\x1d\n" +
	"\n" +
	"proto_file\x18\x01 \x01(\tR\tprotoFile\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12G\n" +
	"\x0erollout_config\x18\x03 \x01(\v2 .v1.ProtoconfValue.ConfigRolloutR\rrolloutConfig\x12(\n" +
	"\bmetadata\x18\x04 \x01(\v2\f.v1.MetadataR\bmetadata\x1a\xb9\x05\n" +
	"\rConfigRollout\x12M\n" +
	"\x15default_cooldown_time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x13defaultCooldownTime\x12Q\n" +
	"\x17default_expiration_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x15defaultExpirationTime\x12>\n" +
	"\x06stages\x18\x03 \x03(\v2&.v1.ProtoconfValue.ConfigRollout.StageR\x06stages\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x1a\xa7\x03\n" +
	"\x05Stage\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1e\n" +
	"\n" +
	"percentile\x18\x02 \x01(\rR\n" +
	"percentile\x12J\n" +
	"\x06labels\x18\x03 \x03(\v22.v1.ProtoconfValue.ConfigRollout.Stage.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06manual\x18\x04 \x01(\bR\x06manual\x125\n" +
	"\bcooldown\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bcooldown\x129\n" +
	"\n" +
	"expiration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"expiration\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\bMetadata\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\x12'\n" +
	"\x0fcommitter_email\x18\x02 \x01(\tR\x0ecommitterEmail\x12!\n" +
	"\fauthor_email\x18\x03 \x01(\tR\vauthorEmail\x12=\n" +
	"\fcommitted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\x12;\n" +
	"\vauthored_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"authoredAt\x12;\n" +
	"\vinserted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"insertedAt\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannelBY\n" +
	"\x1acom.protoconf.datatypes.v1Z;github.com/protoconf/protoconf/datatypes/proto/v1;datatypesb\x06proto3"

var (
	file_datatypes_proto_v1_protoconf_value_proto_rawDescOnce sync.Once
	file_datatypes_proto_v1_protoconf_value_proto_rawDescData []byte
)

func file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP() []byte {
	file_datatypes_proto_v1_protoconf_value_proto_rawDescOnce.Do(func() {
		file_datatypes_proto_v1_protoconf_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatypes_proto_v1_protoconf_value_proto_rawDesc), len(file_datatypes_proto_v1_protoconf_value_proto_rawDesc)))
	})
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescData
}

var file_datatypes_proto_v1_protoconf_value_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_datatypes_proto_v1_protoconf_value_proto_goTypes = []any{
	(*ProtoconfValue)(nil),                     // 0: v1.ProtoconfValue
	(*Metadata)(nil),                           // 1: v1.Metadata
	(*ProtoconfValue_ConfigRollout)(nil),       // 2: v1.ProtoconfValue.ConfigRollout
	(*ProtoconfValue_ConfigRollout_Stage)(nil), // 3: v1.ProtoconfValue.ConfigRollout.Stage
	nil,                           // 4: v1.ProtoconfValue.ConfigRollout.Stage.LabelsEntry
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
}
var file_datatypes_proto_v1_protoconf_value_proto_depIdxs = []int32{
	5,  // 0: v1.ProtoconfValue.value:type_name -> google.protobuf.Any
	2,  // 1: v1.ProtoconfValue.rollout_config:type_name -> v1.ProtoconfValue.ConfigRollout
	1,  // 2: v1.ProtoconfValue.metadata:type_name -> v1.Metadata
	6,  // 3: v1.Metadata.committed_at:type_name -> google.protobuf.Timestamp
	6,  // 4: v1.Metadata.authored_at:type_name -> google.protobuf.Timestamp
	6,  // 5: v1.Metadata.inserted_at:type_name -> google.protobuf.Timestamp
	7,  // 6: v1.ProtoconfValue.ConfigRollout.default_cooldown_time:type_name -> google.protobuf.Duration
	7,  // 7: v1.ProtoconfValue.ConfigRollout.default_expiration_time:type_name -> google.protobuf.Duration
	3,  // 8: v1.ProtoconfValue.ConfigRollout.stages:type_name -> v1.ProtoconfValue.ConfigRollout.Stage
	4,  // 9: v1.ProtoconfValue.ConfigRollout.Stage.labels:type_name -> v1.ProtoconfValue.ConfigRollout.Stage.LabelsEntry
	7,  // 10: v1.ProtoconfValue.ConfigRollout.Stage.cooldown:type_name -> google.protobuf.Duration
	7,  // 11: v1.ProtoconfValue.ConfigRollout.Stage.expiration:type_name -> google.protobuf.Duration
	6,  // 12: v1.ProtoconfValue.ConfigRollout.Stage.expires_at:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_datatypes_proto_v1_protoconf_value_proto_init() }
func file_datatypes_proto_v1_protoconf_value_proto_init() {
	if File_datatypes_proto_v1_protoconf_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatypes_proto_v1_protoconf_value_proto_rawDesc), len(file_datatypes_proto_v1_protoconf_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatypes_proto_v1_protoconf_value_proto_goTypes,
		DependencyIndexes: file_datatypes_proto_v1_protoconf_value_proto_depIdxs,
		MessageInfos:      file_datatypes_proto_v1_protoconf_value_proto_msgTypes,
	}.Build()
	File_datatypes_proto_v1_protoconf_value_proto = out.File
	file_datatypes_proto_v1_protoconf_value_proto_goTypes = nil
	file_datatypes_proto_v1_protoconf_value_proto_depIdxs = nil
}
