// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: datatypes/proto/v1/protoconf_value.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProtoconfValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoFile string            `protobuf:"bytes,1,opt,name=proto_file,json=protoFile,proto3" json:"proto_file,omitempty"`
	Value     *any.Any          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Secrets   []*SecretMetadata `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty"`
}

func (x *ProtoconfValue) Reset() {
	*x = ProtoconfValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoconfValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoconfValue) ProtoMessage() {}

func (x *ProtoconfValue) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoconfValue.ProtoReflect.Descriptor instead.
func (*ProtoconfValue) Descriptor() ([]byte, []int) {
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoconfValue) GetProtoFile() string {
	if x != nil {
		return x.ProtoFile
	}
	return ""
}

func (x *ProtoconfValue) GetValue() *any.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProtoconfValue) GetSecrets() []*SecretMetadata {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type SecretMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos int32 `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Len int32 `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *SecretMetadata) Reset() {
	*x = SecretMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMetadata) ProtoMessage() {}

func (x *SecretMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_datatypes_proto_v1_protoconf_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMetadata.ProtoReflect.Descriptor instead.
func (*SecretMetadata) Descriptor() ([]byte, []int) {
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP(), []int{1}
}

func (x *SecretMetadata) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *SecretMetadata) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

var File_datatypes_proto_v1_protoconf_value_proto protoreflect.FileDescriptor

var file_datatypes_proto_v1_protoconf_value_proto_rawDesc = []byte{
	0x0a, 0x28, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x19,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x07, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x73, 0x22, 0x34, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x42, 0x1c, 0x0a, 0x1a, 0x63,
	0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_datatypes_proto_v1_protoconf_value_proto_rawDescOnce sync.Once
	file_datatypes_proto_v1_protoconf_value_proto_rawDescData = file_datatypes_proto_v1_protoconf_value_proto_rawDesc
)

func file_datatypes_proto_v1_protoconf_value_proto_rawDescGZIP() []byte {
	file_datatypes_proto_v1_protoconf_value_proto_rawDescOnce.Do(func() {
		file_datatypes_proto_v1_protoconf_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_datatypes_proto_v1_protoconf_value_proto_rawDescData)
	})
	return file_datatypes_proto_v1_protoconf_value_proto_rawDescData
}

var file_datatypes_proto_v1_protoconf_value_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datatypes_proto_v1_protoconf_value_proto_goTypes = []interface{}{
	(*ProtoconfValue)(nil), // 0: v1.ProtoconfValue
	(*SecretMetadata)(nil), // 1: v1.SecretMetadata
	(*any.Any)(nil),        // 2: google.protobuf.Any
}
var file_datatypes_proto_v1_protoconf_value_proto_depIdxs = []int32{
	2, // 0: v1.ProtoconfValue.value:type_name -> google.protobuf.Any
	1, // 1: v1.ProtoconfValue.secrets:type_name -> v1.SecretMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_datatypes_proto_v1_protoconf_value_proto_init() }
func file_datatypes_proto_v1_protoconf_value_proto_init() {
	if File_datatypes_proto_v1_protoconf_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datatypes_proto_v1_protoconf_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoconfValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datatypes_proto_v1_protoconf_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datatypes_proto_v1_protoconf_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatypes_proto_v1_protoconf_value_proto_goTypes,
		DependencyIndexes: file_datatypes_proto_v1_protoconf_value_proto_depIdxs,
		MessageInfos:      file_datatypes_proto_v1_protoconf_value_proto_msgTypes,
	}.Build()
	File_datatypes_proto_v1_protoconf_value_proto = out.File
	file_datatypes_proto_v1_protoconf_value_proto_rawDesc = nil
	file_datatypes_proto_v1_protoconf_value_proto_goTypes = nil
	file_datatypes_proto_v1_protoconf_value_proto_depIdxs = nil
}
