# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: agent/api/proto/v1/protoconf_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.any_pb2
import agent.api.proto.v1.protoconf_service_pb2


class ProtoconfServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SubscribeForConfig(self, stream: 'grpclib.server.Stream[agent.api.proto.v1.protoconf_service_pb2.ConfigSubscriptionRequest, agent.api.proto.v1.protoconf_service_pb2.ConfigUpdate]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/v1.ProtoconfService/SubscribeForConfig': grpclib.const.Handler(
                self.SubscribeForConfig,
                grpclib.const.Cardinality.UNARY_STREAM,
                agent.api.proto.v1.protoconf_service_pb2.ConfigSubscriptionRequest,
                agent.api.proto.v1.protoconf_service_pb2.ConfigUpdate,
            ),
        }


class ProtoconfServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SubscribeForConfig = grpclib.client.UnaryStreamMethod(
            channel,
            '/v1.ProtoconfService/SubscribeForConfig',
            agent.api.proto.v1.protoconf_service_pb2.ConfigSubscriptionRequest,
            agent.api.proto.v1.protoconf_service_pb2.ConfigUpdate,
        )
