# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent/api/proto/v1/protoconf_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent/api/proto/v1/protoconf_service.proto',
  package='v1',
  syntax='proto3',
  serialized_options=_b('\n\032com.protoconf.agent.api.v1'),
  serialized_pb=_b('\n*agent/api/proto/v1/protoconf_service.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\")\n\x19\x43onfigSubscriptionRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"3\n\x0c\x43onfigUpdate\x12#\n\x05value\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any2[\n\x10ProtoconfService\x12G\n\x12SubscribeForConfig\x12\x1d.v1.ConfigSubscriptionRequest\x1a\x10.v1.ConfigUpdate0\x01\x42\x1c\n\x1a\x63om.protoconf.agent.api.v1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_CONFIGSUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='ConfigSubscriptionRequest',
  full_name='v1.ConfigSubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='v1.ConfigSubscriptionRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=118,
)


_CONFIGUPDATE = _descriptor.Descriptor(
  name='ConfigUpdate',
  full_name='v1.ConfigUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v1.ConfigUpdate.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=171,
)

_CONFIGUPDATE.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['ConfigSubscriptionRequest'] = _CONFIGSUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['ConfigUpdate'] = _CONFIGUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigSubscriptionRequest = _reflection.GeneratedProtocolMessageType('ConfigSubscriptionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGSUBSCRIPTIONREQUEST,
  __module__ = 'agent.api.proto.v1.protoconf_service_pb2'
  # @@protoc_insertion_point(class_scope:v1.ConfigSubscriptionRequest)
  ))
_sym_db.RegisterMessage(ConfigSubscriptionRequest)

ConfigUpdate = _reflection.GeneratedProtocolMessageType('ConfigUpdate', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGUPDATE,
  __module__ = 'agent.api.proto.v1.protoconf_service_pb2'
  # @@protoc_insertion_point(class_scope:v1.ConfigUpdate)
  ))
_sym_db.RegisterMessage(ConfigUpdate)


DESCRIPTOR._options = None

_PROTOCONFSERVICE = _descriptor.ServiceDescriptor(
  name='ProtoconfService',
  full_name='v1.ProtoconfService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=173,
  serialized_end=264,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeForConfig',
    full_name='v1.ProtoconfService.SubscribeForConfig',
    index=0,
    containing_service=None,
    input_type=_CONFIGSUBSCRIPTIONREQUEST,
    output_type=_CONFIGUPDATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROTOCONFSERVICE)

DESCRIPTOR.services_by_name['ProtoconfService'] = _PROTOCONFSERVICE

# @@protoc_insertion_point(module_scope)
