// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: examples/protoconf/src/crawler/crawler.proto

package crawler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrawlerService_AdminPermission int32

const (
	CrawlerService_READ_WRITE CrawlerService_AdminPermission = 0
	CrawlerService_GOD_MODE   CrawlerService_AdminPermission = 1
)

// Enum value maps for CrawlerService_AdminPermission.
var (
	CrawlerService_AdminPermission_name = map[int32]string{
		0: "READ_WRITE",
		1: "GOD_MODE",
	}
	CrawlerService_AdminPermission_value = map[string]int32{
		"READ_WRITE": 0,
		"GOD_MODE":   1,
	}
)

func (x CrawlerService_AdminPermission) Enum() *CrawlerService_AdminPermission {
	p := new(CrawlerService_AdminPermission)
	*p = x
	return p
}

func (x CrawlerService_AdminPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrawlerService_AdminPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_protoconf_src_crawler_crawler_proto_enumTypes[0].Descriptor()
}

func (CrawlerService_AdminPermission) Type() protoreflect.EnumType {
	return &file_examples_protoconf_src_crawler_crawler_proto_enumTypes[0]
}

func (x CrawlerService_AdminPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrawlerService_AdminPermission.Descriptor instead.
func (CrawlerService_AdminPermission) EnumDescriptor() ([]byte, []int) {
	return file_examples_protoconf_src_crawler_crawler_proto_rawDescGZIP(), []int{1, 0}
}

type Crawler struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserAgent       string                 `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	HttpTimeout     int32                  `protobuf:"varint,2,opt,name=http_timeout,json=httpTimeout,proto3" json:"http_timeout,omitempty"`
	FollowRedirects bool                   `protobuf:"varint,3,opt,name=follow_redirects,json=followRedirects,proto3" json:"follow_redirects,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Crawler) Reset() {
	*x = Crawler{}
	mi := &file_examples_protoconf_src_crawler_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Crawler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crawler) ProtoMessage() {}

func (x *Crawler) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protoconf_src_crawler_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crawler.ProtoReflect.Descriptor instead.
func (*Crawler) Descriptor() ([]byte, []int) {
	return file_examples_protoconf_src_crawler_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *Crawler) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Crawler) GetHttpTimeout() int32 {
	if x != nil {
		return x.HttpTimeout
	}
	return 0
}

func (x *Crawler) GetFollowRedirects() bool {
	if x != nil {
		return x.FollowRedirects
	}
	return false
}

type CrawlerService struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Crawlers      []*Crawler                                `protobuf:"bytes,1,rep,name=crawlers,proto3" json:"crawlers,omitempty"`
	Admins        map[string]CrawlerService_AdminPermission `protobuf:"bytes,2,rep,name=admins,proto3" json:"admins,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=CrawlerService_AdminPermission"`
	LogLevel      int32                                     `protobuf:"varint,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlerService) Reset() {
	*x = CrawlerService{}
	mi := &file_examples_protoconf_src_crawler_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlerService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerService) ProtoMessage() {}

func (x *CrawlerService) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protoconf_src_crawler_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerService.ProtoReflect.Descriptor instead.
func (*CrawlerService) Descriptor() ([]byte, []int) {
	return file_examples_protoconf_src_crawler_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlerService) GetCrawlers() []*Crawler {
	if x != nil {
		return x.Crawlers
	}
	return nil
}

func (x *CrawlerService) GetAdmins() map[string]CrawlerService_AdminPermission {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *CrawlerService) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

var File_examples_protoconf_src_crawler_crawler_proto protoreflect.FileDescriptor

const file_examples_protoconf_src_crawler_crawler_proto_rawDesc = "" +
	"\n" +
	",examples/protoconf/src/crawler/crawler.proto\"v\n" +
	"\aCrawler\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tR\tuserAgent\x12!\n" +
	"\fhttp_timeout\x18\x02 \x01(\x05R\vhttpTimeout\x12)\n" +
	"\x10follow_redirects\x18\x03 \x01(\bR\x0ffollowRedirects\"\x95\x02\n" +
	"\x0eCrawlerService\x12$\n" +
	"\bcrawlers\x18\x01 \x03(\v2\b.CrawlerR\bcrawlers\x123\n" +
	"\x06admins\x18\x02 \x03(\v2\x1b.CrawlerService.AdminsEntryR\x06admins\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\x05R\blogLevel\x1aZ\n" +
	"\vAdminsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1f.CrawlerService.AdminPermissionR\x05value:\x028\x01\"/\n" +
	"\x0fAdminPermission\x12\x0e\n" +
	"\n" +
	"READ_WRITE\x10\x00\x12\f\n" +
	"\bGOD_MODE\x10\x01B_\n" +
	"\x1ecom.protoconf.examples.crawlerZ=github.com/protoconf/protoconf/examples/protoconf/src/crawlerb\x06proto3"

var (
	file_examples_protoconf_src_crawler_crawler_proto_rawDescOnce sync.Once
	file_examples_protoconf_src_crawler_crawler_proto_rawDescData []byte
)

func file_examples_protoconf_src_crawler_crawler_proto_rawDescGZIP() []byte {
	file_examples_protoconf_src_crawler_crawler_proto_rawDescOnce.Do(func() {
		file_examples_protoconf_src_crawler_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protoconf_src_crawler_crawler_proto_rawDesc), len(file_examples_protoconf_src_crawler_crawler_proto_rawDesc)))
	})
	return file_examples_protoconf_src_crawler_crawler_proto_rawDescData
}

var file_examples_protoconf_src_crawler_crawler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_protoconf_src_crawler_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_protoconf_src_crawler_crawler_proto_goTypes = []any{
	(CrawlerService_AdminPermission)(0), // 0: CrawlerService.AdminPermission
	(*Crawler)(nil),                     // 1: Crawler
	(*CrawlerService)(nil),              // 2: CrawlerService
	nil,                                 // 3: CrawlerService.AdminsEntry
}
var file_examples_protoconf_src_crawler_crawler_proto_depIdxs = []int32{
	1, // 0: CrawlerService.crawlers:type_name -> Crawler
	3, // 1: CrawlerService.admins:type_name -> CrawlerService.AdminsEntry
	0, // 2: CrawlerService.AdminsEntry.value:type_name -> CrawlerService.AdminPermission
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_examples_protoconf_src_crawler_crawler_proto_init() }
func file_examples_protoconf_src_crawler_crawler_proto_init() {
	if File_examples_protoconf_src_crawler_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protoconf_src_crawler_crawler_proto_rawDesc), len(file_examples_protoconf_src_crawler_crawler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protoconf_src_crawler_crawler_proto_goTypes,
		DependencyIndexes: file_examples_protoconf_src_crawler_crawler_proto_depIdxs,
		EnumInfos:         file_examples_protoconf_src_crawler_crawler_proto_enumTypes,
		MessageInfos:      file_examples_protoconf_src_crawler_crawler_proto_msgTypes,
	}.Build()
	File_examples_protoconf_src_crawler_crawler_proto = out.File
	file_examples_protoconf_src_crawler_crawler_proto_goTypes = nil
	file_examples_protoconf_src_crawler_crawler_proto_depIdxs = nil
}
