# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datatypes/proto/v1/protoconf_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='datatypes/proto/v1/protoconf_value.proto',
  package='v1',
  syntax='proto3',
  serialized_options=_b('\n\032com.protoconf.datatypes.v1'),
  serialized_pb=_b('\n(datatypes/proto/v1/protoconf_value.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\"I\n\x0eProtoconfValue\x12\x12\n\nproto_file\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\x1c\n\x1a\x63om.protoconf.datatypes.v1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_PROTOCONFVALUE = _descriptor.Descriptor(
  name='ProtoconfValue',
  full_name='v1.ProtoconfValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_file', full_name='v1.ProtoconfValue.proto_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='v1.ProtoconfValue.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=148,
)

_PROTOCONFVALUE.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['ProtoconfValue'] = _PROTOCONFVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoconfValue = _reflection.GeneratedProtocolMessageType('ProtoconfValue', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCONFVALUE,
  __module__ = 'datatypes.proto.v1.protoconf_value_pb2'
  # @@protoc_insertion_point(class_scope:v1.ProtoconfValue)
  ))
_sym_db.RegisterMessage(ProtoconfValue)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
