// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: agent/api/proto/v1/protoconf_service.proto

package protoconfservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtoconfService_SubscribeForConfig_FullMethodName = "/v1.ProtoconfService/SubscribeForConfig"
	ProtoconfService_GetConfig_FullMethodName          = "/v1.ProtoconfService/GetConfig"
)

// ProtoconfServiceClient is the client API for ProtoconfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoconfServiceClient interface {
	SubscribeForConfig(ctx context.Context, in *ConfigSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error)
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigUpdate, error)
}

type protoconfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoconfServiceClient(cc grpc.ClientConnInterface) ProtoconfServiceClient {
	return &protoconfServiceClient{cc}
}

func (c *protoconfServiceClient) SubscribeForConfig(ctx context.Context, in *ConfigSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProtoconfService_ServiceDesc.Streams[0], ProtoconfService_SubscribeForConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigSubscriptionRequest, ConfigUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtoconfService_SubscribeForConfigClient = grpc.ServerStreamingClient[ConfigUpdate]

func (c *protoconfServiceClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigUpdate)
	err := c.cc.Invoke(ctx, ProtoconfService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoconfServiceServer is the server API for ProtoconfService service.
// All implementations must embed UnimplementedProtoconfServiceServer
// for forward compatibility.
type ProtoconfServiceServer interface {
	SubscribeForConfig(*ConfigSubscriptionRequest, grpc.ServerStreamingServer[ConfigUpdate]) error
	GetConfig(context.Context, *ConfigRequest) (*ConfigUpdate, error)
	mustEmbedUnimplementedProtoconfServiceServer()
}

// UnimplementedProtoconfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoconfServiceServer struct{}

func (UnimplementedProtoconfServiceServer) SubscribeForConfig(*ConfigSubscriptionRequest, grpc.ServerStreamingServer[ConfigUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeForConfig not implemented")
}
func (UnimplementedProtoconfServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedProtoconfServiceServer) mustEmbedUnimplementedProtoconfServiceServer() {}
func (UnimplementedProtoconfServiceServer) testEmbeddedByValue()                          {}

// UnsafeProtoconfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoconfServiceServer will
// result in compilation errors.
type UnsafeProtoconfServiceServer interface {
	mustEmbedUnimplementedProtoconfServiceServer()
}

func RegisterProtoconfServiceServer(s grpc.ServiceRegistrar, srv ProtoconfServiceServer) {
	// If the following call pancis, it indicates UnimplementedProtoconfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoconfService_ServiceDesc, srv)
}

func _ProtoconfService_SubscribeForConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigSubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProtoconfServiceServer).SubscribeForConfig(m, &grpc.GenericServerStream[ConfigSubscriptionRequest, ConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtoconfService_SubscribeForConfigServer = grpc.ServerStreamingServer[ConfigUpdate]

func _ProtoconfService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoconfServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoconfService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoconfServiceServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoconfService_ServiceDesc is the grpc.ServiceDesc for ProtoconfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoconfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ProtoconfService",
	HandlerType: (*ProtoconfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ProtoconfService_GetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeForConfig",
			Handler:       _ProtoconfService_SubscribeForConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/api/proto/v1/protoconf_service.proto",
}
