// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: agent/api/proto/v1/protoconf_service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ConfigSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ConfigSubscriptionRequest) Reset() {
	*x = ConfigSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSubscriptionRequest) ProtoMessage() {}

func (x *ConfigSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ConfigSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_v1_protoconf_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigSubscriptionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *any.Any `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_v1_protoconf_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigUpdate) GetValue() *any.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_agent_api_proto_v1_protoconf_service_proto protoreflect.FileDescriptor

var file_agent_api_proto_v1_protoconf_service_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x19, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x3a, 0x0a, 0x0c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x5b, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x12,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x30, 0x01, 0x42, 0x1c, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_api_proto_v1_protoconf_service_proto_rawDescOnce sync.Once
	file_agent_api_proto_v1_protoconf_service_proto_rawDescData = file_agent_api_proto_v1_protoconf_service_proto_rawDesc
)

func file_agent_api_proto_v1_protoconf_service_proto_rawDescGZIP() []byte {
	file_agent_api_proto_v1_protoconf_service_proto_rawDescOnce.Do(func() {
		file_agent_api_proto_v1_protoconf_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_api_proto_v1_protoconf_service_proto_rawDescData)
	})
	return file_agent_api_proto_v1_protoconf_service_proto_rawDescData
}

var file_agent_api_proto_v1_protoconf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_api_proto_v1_protoconf_service_proto_goTypes = []interface{}{
	(*ConfigSubscriptionRequest)(nil), // 0: v1.ConfigSubscriptionRequest
	(*ConfigUpdate)(nil),              // 1: v1.ConfigUpdate
	(*any.Any)(nil),                   // 2: google.protobuf.Any
}
var file_agent_api_proto_v1_protoconf_service_proto_depIdxs = []int32{
	2, // 0: v1.ConfigUpdate.value:type_name -> google.protobuf.Any
	0, // 1: v1.ProtoconfService.SubscribeForConfig:input_type -> v1.ConfigSubscriptionRequest
	1, // 2: v1.ProtoconfService.SubscribeForConfig:output_type -> v1.ConfigUpdate
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_api_proto_v1_protoconf_service_proto_init() }
func file_agent_api_proto_v1_protoconf_service_proto_init() {
	if File_agent_api_proto_v1_protoconf_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_api_proto_v1_protoconf_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_api_proto_v1_protoconf_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_api_proto_v1_protoconf_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_api_proto_v1_protoconf_service_proto_goTypes,
		DependencyIndexes: file_agent_api_proto_v1_protoconf_service_proto_depIdxs,
		MessageInfos:      file_agent_api_proto_v1_protoconf_service_proto_msgTypes,
	}.Build()
	File_agent_api_proto_v1_protoconf_service_proto = out.File
	file_agent_api_proto_v1_protoconf_service_proto_rawDesc = nil
	file_agent_api_proto_v1_protoconf_service_proto_goTypes = nil
	file_agent_api_proto_v1_protoconf_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProtoconfServiceClient is the client API for ProtoconfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProtoconfServiceClient interface {
	SubscribeForConfig(ctx context.Context, in *ConfigSubscriptionRequest, opts ...grpc.CallOption) (ProtoconfService_SubscribeForConfigClient, error)
}

type protoconfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoconfServiceClient(cc grpc.ClientConnInterface) ProtoconfServiceClient {
	return &protoconfServiceClient{cc}
}

func (c *protoconfServiceClient) SubscribeForConfig(ctx context.Context, in *ConfigSubscriptionRequest, opts ...grpc.CallOption) (ProtoconfService_SubscribeForConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProtoconfService_serviceDesc.Streams[0], "/v1.ProtoconfService/SubscribeForConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &protoconfServiceSubscribeForConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProtoconfService_SubscribeForConfigClient interface {
	Recv() (*ConfigUpdate, error)
	grpc.ClientStream
}

type protoconfServiceSubscribeForConfigClient struct {
	grpc.ClientStream
}

func (x *protoconfServiceSubscribeForConfigClient) Recv() (*ConfigUpdate, error) {
	m := new(ConfigUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProtoconfServiceServer is the server API for ProtoconfService service.
type ProtoconfServiceServer interface {
	SubscribeForConfig(*ConfigSubscriptionRequest, ProtoconfService_SubscribeForConfigServer) error
}

// UnimplementedProtoconfServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProtoconfServiceServer struct {
}

func (*UnimplementedProtoconfServiceServer) SubscribeForConfig(*ConfigSubscriptionRequest, ProtoconfService_SubscribeForConfigServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeForConfig not implemented")
}

func RegisterProtoconfServiceServer(s *grpc.Server, srv ProtoconfServiceServer) {
	s.RegisterService(&_ProtoconfService_serviceDesc, srv)
}

func _ProtoconfService_SubscribeForConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigSubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProtoconfServiceServer).SubscribeForConfig(m, &protoconfServiceSubscribeForConfigServer{stream})
}

type ProtoconfService_SubscribeForConfigServer interface {
	Send(*ConfigUpdate) error
	grpc.ServerStream
}

type protoconfServiceSubscribeForConfigServer struct {
	grpc.ServerStream
}

func (x *protoconfServiceSubscribeForConfigServer) Send(m *ConfigUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var _ProtoconfService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ProtoconfService",
	HandlerType: (*ProtoconfServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeForConfig",
			Handler:       _ProtoconfService_SubscribeForConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/api/proto/v1/protoconf_service.proto",
}
