// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: agent/api/proto/v1/protoconf_service.proto

package protoconfservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSubscriptionRequest) Reset() {
	*x = ConfigSubscriptionRequest{}
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSubscriptionRequest) ProtoMessage() {}

func (x *ConfigSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ConfigSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_v1_protoconf_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigSubscriptionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigSubscriptionRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_v1_protoconf_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_proto_v1_protoconf_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_api_proto_v1_protoconf_service_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigUpdate) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_api_proto_v1_protoconf_service_proto protoreflect.FileDescriptor

const file_agent_api_proto_v1_protoconf_service_proto_rawDesc = "" +
	"\n" +
	"*agent/api/proto/v1/protoconf_service.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\"I\n" +
	"\x19ConfigSubscriptionRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"=\n" +
	"\rConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"P\n" +
	"\fConfigUpdate\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x8d\x01\n" +
	"\x10ProtoconfService\x12G\n" +
	"\x12SubscribeForConfig\x12\x1d.v1.ConfigSubscriptionRequest\x1a\x10.v1.ConfigUpdate0\x01\x120\n" +
	"\tGetConfig\x12\x11.v1.ConfigRequest\x1a\x10.v1.ConfigUpdateB`\n" +
	"\x1acom.protoconf.agent.api.v1ZBgithub.com/protoconf/protoconf/agent/api/proto/v1;protoconfserviceb\x06proto3"

var (
	file_agent_api_proto_v1_protoconf_service_proto_rawDescOnce sync.Once
	file_agent_api_proto_v1_protoconf_service_proto_rawDescData []byte
)

func file_agent_api_proto_v1_protoconf_service_proto_rawDescGZIP() []byte {
	file_agent_api_proto_v1_protoconf_service_proto_rawDescOnce.Do(func() {
		file_agent_api_proto_v1_protoconf_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_api_proto_v1_protoconf_service_proto_rawDesc), len(file_agent_api_proto_v1_protoconf_service_proto_rawDesc)))
	})
	return file_agent_api_proto_v1_protoconf_service_proto_rawDescData
}

var file_agent_api_proto_v1_protoconf_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agent_api_proto_v1_protoconf_service_proto_goTypes = []any{
	(*ConfigSubscriptionRequest)(nil), // 0: v1.ConfigSubscriptionRequest
	(*ConfigRequest)(nil),             // 1: v1.ConfigRequest
	(*ConfigUpdate)(nil),              // 2: v1.ConfigUpdate
	(*anypb.Any)(nil),                 // 3: google.protobuf.Any
}
var file_agent_api_proto_v1_protoconf_service_proto_depIdxs = []int32{
	3, // 0: v1.ConfigUpdate.value:type_name -> google.protobuf.Any
	0, // 1: v1.ProtoconfService.SubscribeForConfig:input_type -> v1.ConfigSubscriptionRequest
	1, // 2: v1.ProtoconfService.GetConfig:input_type -> v1.ConfigRequest
	2, // 3: v1.ProtoconfService.SubscribeForConfig:output_type -> v1.ConfigUpdate
	2, // 4: v1.ProtoconfService.GetConfig:output_type -> v1.ConfigUpdate
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_api_proto_v1_protoconf_service_proto_init() }
func file_agent_api_proto_v1_protoconf_service_proto_init() {
	if File_agent_api_proto_v1_protoconf_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_api_proto_v1_protoconf_service_proto_rawDesc), len(file_agent_api_proto_v1_protoconf_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_api_proto_v1_protoconf_service_proto_goTypes,
		DependencyIndexes: file_agent_api_proto_v1_protoconf_service_proto_depIdxs,
		MessageInfos:      file_agent_api_proto_v1_protoconf_service_proto_msgTypes,
	}.Build()
	File_agent_api_proto_v1_protoconf_service_proto = out.File
	file_agent_api_proto_v1_protoconf_service_proto_goTypes = nil
	file_agent_api_proto_v1_protoconf_service_proto_depIdxs = nil
}
