// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: compiler/module/v1/remote_repo.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteRepo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Url   string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Types that are valid to be assigned to Pin:
	//
	//	*RemoteRepo_Tag
	//	*RemoteRepo_Branch
	//	*RemoteRepo_Commit
	//	*RemoteRepo_Checksum
	Pin                  isRemoteRepo_Pin       `protobuf_oneof:"pin"`
	SourcePath           string                 `protobuf:"bytes,7,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	AdditionalProtoDirs  []string               `protobuf:"bytes,8,rep,name=additional_proto_dirs,json=additionalProtoDirs,proto3" json:"additional_proto_dirs,omitempty"`
	ExcludeFileRegexps   []string               `protobuf:"bytes,13,rep,name=exclude_file_regexps,json=excludeFileRegexps,proto3" json:"exclude_file_regexps,omitempty"`
	Integrity            string                 `protobuf:"bytes,10,opt,name=integrity,proto3" json:"integrity,omitempty"`
	GetterUrl            string                 `protobuf:"bytes,11,opt,name=getter_url,json=getterUrl,proto3" json:"getter_url,omitempty"`
	FileDescriptorSetSum string                 `protobuf:"bytes,12,opt,name=file_descriptor_set_sum,json=fileDescriptorSetSum,proto3" json:"file_descriptor_set_sum,omitempty"`
	Deps                 map[string]*RemoteRepo `protobuf:"bytes,100,rep,name=deps,proto3" json:"deps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RemoteRepo) Reset() {
	*x = RemoteRepo{}
	mi := &file_compiler_module_v1_remote_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteRepo) ProtoMessage() {}

func (x *RemoteRepo) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_module_v1_remote_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteRepo.ProtoReflect.Descriptor instead.
func (*RemoteRepo) Descriptor() ([]byte, []int) {
	return file_compiler_module_v1_remote_repo_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteRepo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RemoteRepo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RemoteRepo) GetPin() isRemoteRepo_Pin {
	if x != nil {
		return x.Pin
	}
	return nil
}

func (x *RemoteRepo) GetTag() string {
	if x != nil {
		if x, ok := x.Pin.(*RemoteRepo_Tag); ok {
			return x.Tag
		}
	}
	return ""
}

func (x *RemoteRepo) GetBranch() string {
	if x != nil {
		if x, ok := x.Pin.(*RemoteRepo_Branch); ok {
			return x.Branch
		}
	}
	return ""
}

func (x *RemoteRepo) GetCommit() string {
	if x != nil {
		if x, ok := x.Pin.(*RemoteRepo_Commit); ok {
			return x.Commit
		}
	}
	return ""
}

func (x *RemoteRepo) GetChecksum() string {
	if x != nil {
		if x, ok := x.Pin.(*RemoteRepo_Checksum); ok {
			return x.Checksum
		}
	}
	return ""
}

func (x *RemoteRepo) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *RemoteRepo) GetAdditionalProtoDirs() []string {
	if x != nil {
		return x.AdditionalProtoDirs
	}
	return nil
}

func (x *RemoteRepo) GetExcludeFileRegexps() []string {
	if x != nil {
		return x.ExcludeFileRegexps
	}
	return nil
}

func (x *RemoteRepo) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

func (x *RemoteRepo) GetGetterUrl() string {
	if x != nil {
		return x.GetterUrl
	}
	return ""
}

func (x *RemoteRepo) GetFileDescriptorSetSum() string {
	if x != nil {
		return x.FileDescriptorSetSum
	}
	return ""
}

func (x *RemoteRepo) GetDeps() map[string]*RemoteRepo {
	if x != nil {
		return x.Deps
	}
	return nil
}

type isRemoteRepo_Pin interface {
	isRemoteRepo_Pin()
}

type RemoteRepo_Tag struct {
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3,oneof"`
}

type RemoteRepo_Branch struct {
	Branch string `protobuf:"bytes,4,opt,name=branch,proto3,oneof"`
}

type RemoteRepo_Commit struct {
	Commit string `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

type RemoteRepo_Checksum struct {
	Checksum string `protobuf:"bytes,6,opt,name=checksum,proto3,oneof"` // How to validate the integrity of a file if url leads to an archive
}

func (*RemoteRepo_Tag) isRemoteRepo_Pin() {}

func (*RemoteRepo_Branch) isRemoteRepo_Pin() {}

func (*RemoteRepo_Commit) isRemoteRepo_Pin() {}

func (*RemoteRepo_Checksum) isRemoteRepo_Pin() {}

type ModuleServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoconfPath string                 `protobuf:"bytes,1,opt,name=protoconf_path,json=protoconfPath,proto3" json:"protoconf_path,omitempty"`
	CacheDir      string                 `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	LockFile      string                 `protobuf:"bytes,3,opt,name=lock_file,json=lockFile,proto3" json:"lock_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleServiceConfig) Reset() {
	*x = ModuleServiceConfig{}
	mi := &file_compiler_module_v1_remote_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleServiceConfig) ProtoMessage() {}

func (x *ModuleServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_module_v1_remote_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleServiceConfig.ProtoReflect.Descriptor instead.
func (*ModuleServiceConfig) Descriptor() ([]byte, []int) {
	return file_compiler_module_v1_remote_repo_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleServiceConfig) GetProtoconfPath() string {
	if x != nil {
		return x.ProtoconfPath
	}
	return ""
}

func (x *ModuleServiceConfig) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *ModuleServiceConfig) GetLockFile() string {
	if x != nil {
		return x.LockFile
	}
	return ""
}

var File_compiler_module_v1_remote_repo_proto protoreflect.FileDescriptor

const file_compiler_module_v1_remote_repo_proto_rawDesc = "" +
	"\n" +
	"$compiler/module/v1/remote_repo.proto\x12\x1cprotoconf.compiler.module.v1\"\xc7\x04\n" +
	"\n" +
	"RemoteRepo\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x03tag\x18\x03 \x01(\tH\x00R\x03tag\x12\x18\n" +
	"\x06branch\x18\x04 \x01(\tH\x00R\x06branch\x12\x18\n" +
	"\x06commit\x18\x05 \x01(\tH\x00R\x06commit\x12\x1c\n" +
	"\bchecksum\x18\x06 \x01(\tH\x00R\bchecksum\x12\x1f\n" +
	"\vsource_path\x18\a \x01(\tR\n" +
	"sourcePath\x122\n" +
	"\x15additional_proto_dirs\x18\b \x03(\tR\x13additionalProtoDirs\x120\n" +
	"\x14exclude_file_regexps\x18\r \x03(\tR\x12excludeFileRegexps\x12\x1c\n" +
	"\tintegrity\x18\n" +
	" \x01(\tR\tintegrity\x12\x1d\n" +
	"\n" +
	"getter_url\x18\v \x01(\tR\tgetterUrl\x125\n" +
	"\x17file_descriptor_set_sum\x18\f \x01(\tR\x14fileDescriptorSetSum\x12F\n" +
	"\x04deps\x18d \x03(\v22.protoconf.compiler.module.v1.RemoteRepo.DepsEntryR\x04deps\x1aa\n" +
	"\tDepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.protoconf.compiler.module.v1.RemoteRepoR\x05value:\x028\x01B\x05\n" +
	"\x03pin\"v\n" +
	"\x13ModuleServiceConfig\x12%\n" +
	"\x0eprotoconf_path\x18\x01 \x01(\tR\rprotoconfPath\x12\x1b\n" +
	"\tcache_dir\x18\x02 \x01(\tR\bcacheDir\x12\x1b\n" +
	"\tlock_file\x18\x03 \x01(\tR\blockFileB:Z8github.com/protoconf/protoconf/compiler/module/v1;moduleb\x06proto3"

var (
	file_compiler_module_v1_remote_repo_proto_rawDescOnce sync.Once
	file_compiler_module_v1_remote_repo_proto_rawDescData []byte
)

func file_compiler_module_v1_remote_repo_proto_rawDescGZIP() []byte {
	file_compiler_module_v1_remote_repo_proto_rawDescOnce.Do(func() {
		file_compiler_module_v1_remote_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compiler_module_v1_remote_repo_proto_rawDesc), len(file_compiler_module_v1_remote_repo_proto_rawDesc)))
	})
	return file_compiler_module_v1_remote_repo_proto_rawDescData
}

var file_compiler_module_v1_remote_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_compiler_module_v1_remote_repo_proto_goTypes = []any{
	(*RemoteRepo)(nil),          // 0: protoconf.compiler.module.v1.RemoteRepo
	(*ModuleServiceConfig)(nil), // 1: protoconf.compiler.module.v1.ModuleServiceConfig
	nil,                         // 2: protoconf.compiler.module.v1.RemoteRepo.DepsEntry
}
var file_compiler_module_v1_remote_repo_proto_depIdxs = []int32{
	2, // 0: protoconf.compiler.module.v1.RemoteRepo.deps:type_name -> protoconf.compiler.module.v1.RemoteRepo.DepsEntry
	0, // 1: protoconf.compiler.module.v1.RemoteRepo.DepsEntry.value:type_name -> protoconf.compiler.module.v1.RemoteRepo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_compiler_module_v1_remote_repo_proto_init() }
func file_compiler_module_v1_remote_repo_proto_init() {
	if File_compiler_module_v1_remote_repo_proto != nil {
		return
	}
	file_compiler_module_v1_remote_repo_proto_msgTypes[0].OneofWrappers = []any{
		(*RemoteRepo_Tag)(nil),
		(*RemoteRepo_Branch)(nil),
		(*RemoteRepo_Commit)(nil),
		(*RemoteRepo_Checksum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compiler_module_v1_remote_repo_proto_rawDesc), len(file_compiler_module_v1_remote_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_compiler_module_v1_remote_repo_proto_goTypes,
		DependencyIndexes: file_compiler_module_v1_remote_repo_proto_depIdxs,
		MessageInfos:      file_compiler_module_v1_remote_repo_proto_msgTypes,
	}.Build()
	File_compiler_module_v1_remote_repo_proto = out.File
	file_compiler_module_v1_remote_repo_proto_goTypes = nil
	file_compiler_module_v1_remote_repo_proto_depIdxs = nil
}
