// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: compiler/config/v1/compiler_config.proto

package protoconf_compiler_config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompilerConfig defines the configuration for the protoconf compiler.
type CompilerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Run in interactive REPL mode.
	Repl bool `protobuf:"varint,1,opt,name=repl,proto3" json:"repl,omitempty"`
	// Enable verbose logging.
	VerboseLogging bool `protobuf:"varint,2,opt,name=verbose_logging,json=V,proto3" json:"verbose_logging,omitempty"`
	// Process template files before compiling.
	ProcessTemplates bool `protobuf:"varint,3,opt,name=process_templates,json=process-templates,proto3" json:"process_templates,omitempty"`
	// Write CPU profiling info to this file.
	Cpuprofile string `protobuf:"bytes,4,opt,name=cpuprofile,proto3" json:"cpuprofile,omitempty"`
	// Write memory profiling info to this file.
	Memprofile string `protobuf:"bytes,5,opt,name=memprofile,proto3" json:"memprofile,omitempty"`
	// If set, issue a gRPC request to the compiler service at the given address
	// instead of running the compiler locally.
	CompilerAddress string `protobuf:"bytes,6,opt,name=compiler_address,json=compiler-address,proto3" json:"compiler_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompilerConfig) Reset() {
	*x = CompilerConfig{}
	mi := &file_compiler_config_v1_compiler_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilerConfig) ProtoMessage() {}

func (x *CompilerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_config_v1_compiler_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilerConfig.ProtoReflect.Descriptor instead.
func (*CompilerConfig) Descriptor() ([]byte, []int) {
	return file_compiler_config_v1_compiler_config_proto_rawDescGZIP(), []int{0}
}

func (x *CompilerConfig) GetRepl() bool {
	if x != nil {
		return x.Repl
	}
	return false
}

func (x *CompilerConfig) GetVerboseLogging() bool {
	if x != nil {
		return x.VerboseLogging
	}
	return false
}

func (x *CompilerConfig) GetProcessTemplates() bool {
	if x != nil {
		return x.ProcessTemplates
	}
	return false
}

func (x *CompilerConfig) GetCpuprofile() string {
	if x != nil {
		return x.Cpuprofile
	}
	return ""
}

func (x *CompilerConfig) GetMemprofile() string {
	if x != nil {
		return x.Memprofile
	}
	return ""
}

func (x *CompilerConfig) GetCompilerAddress() string {
	if x != nil {
		return x.CompilerAddress
	}
	return ""
}

var File_compiler_config_v1_compiler_config_proto protoreflect.FileDescriptor

const file_compiler_config_v1_compiler_config_proto_rawDesc = "" +
	"\n" +
	"(compiler/config/v1/compiler_config.proto\x12\x1cprotoconf.compiler.config.v1\"\xda\x01\n" +
	"\x0eCompilerConfig\x12\x12\n" +
	"\x04repl\x18\x01 \x01(\bR\x04repl\x12\x1a\n" +
	"\x0fverbose_logging\x18\x02 \x01(\bR\x01V\x12,\n" +
	"\x11process_templates\x18\x03 \x01(\bR\x11process-templates\x12\x1e\n" +
	"\n" +
	"cpuprofile\x18\x04 \x01(\tR\n" +
	"cpuprofile\x12\x1e\n" +
	"\n" +
	"memprofile\x18\x05 \x01(\tR\n" +
	"memprofile\x12*\n" +
	"\x10compiler_address\x18\x06 \x01(\tR\x10compiler-addressBMZKgithub.com/protoconf/protoconf/compiler/config/v1;protoconf_compiler_configb\x06proto3"

var (
	file_compiler_config_v1_compiler_config_proto_rawDescOnce sync.Once
	file_compiler_config_v1_compiler_config_proto_rawDescData []byte
)

func file_compiler_config_v1_compiler_config_proto_rawDescGZIP() []byte {
	file_compiler_config_v1_compiler_config_proto_rawDescOnce.Do(func() {
		file_compiler_config_v1_compiler_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compiler_config_v1_compiler_config_proto_rawDesc), len(file_compiler_config_v1_compiler_config_proto_rawDesc)))
	})
	return file_compiler_config_v1_compiler_config_proto_rawDescData
}

var file_compiler_config_v1_compiler_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_compiler_config_v1_compiler_config_proto_goTypes = []any{
	(*CompilerConfig)(nil), // 0: protoconf.compiler.config.v1.CompilerConfig
}
var file_compiler_config_v1_compiler_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compiler_config_v1_compiler_config_proto_init() }
func file_compiler_config_v1_compiler_config_proto_init() {
	if File_compiler_config_v1_compiler_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compiler_config_v1_compiler_config_proto_rawDesc), len(file_compiler_config_v1_compiler_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_compiler_config_v1_compiler_config_proto_goTypes,
		DependencyIndexes: file_compiler_config_v1_compiler_config_proto_depIdxs,
		MessageInfos:      file_compiler_config_v1_compiler_config_proto_msgTypes,
	}.Build()
	File_compiler_config_v1_compiler_config_proto = out.File
	file_compiler_config_v1_compiler_config_proto_goTypes = nil
	file_compiler_config_v1_compiler_config_proto_depIdxs = nil
}
