// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: mutate/config/v1/mutate_config.proto

package protoconf_mutate_config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MutateConfig defines the configuration for the protoconf mutate CLI.
type MutateConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The root of protoconf src.
	ProtoconfRoot string `protobuf:"bytes,1,opt,name=protoconf_root,json=root,proto3" json:"protoconf_root,omitempty"`
	// Path to the proto file.
	ProtoFile string `protobuf:"bytes,2,opt,name=proto_file,json=proto,proto3" json:"proto_file,omitempty"`
	// Name of the message inside the proto file.
	ProtoMsg string `protobuf:"bytes,3,opt,name=proto_msg,json=msg,proto3" json:"proto_msg,omitempty"`
	// Mutation server address.
	ServerAddress string `protobuf:"bytes,4,opt,name=server_address,json=addr,proto3" json:"server_address,omitempty"`
	// Path to put the config in.
	ConfigPath string `protobuf:"bytes,5,opt,name=config_path,json=path,proto3" json:"config_path,omitempty"`
	// Metadata string to pass to the pre/post install script.
	MetadataStr string `protobuf:"bytes,6,opt,name=metadata_str,json=metadata,proto3" json:"metadata_str,omitempty"`
	// Fields to set inside the message (key=value pairs).
	Fields []string `protobuf:"bytes,7,rep,name=fields,json=field,proto3" json:"fields,omitempty"`
	// TLS client certificate file.
	TlsCert string `protobuf:"bytes,8,opt,name=tls_cert,json=tls-cert,proto3" json:"tls_cert,omitempty"`
	// TLS client key file.
	TlsKey string `protobuf:"bytes,9,opt,name=tls_key,json=tls-key,proto3" json:"tls_key,omitempty"`
	// TLS CA certificate file.
	TlsCa string `protobuf:"bytes,10,opt,name=tls_ca,json=tls-ca,proto3" json:"tls_ca,omitempty"`
	// Use insecure connection (no TLS).
	InsecureTls   bool `protobuf:"varint,11,opt,name=insecure_tls,json=insecure,proto3" json:"insecure_tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateConfig) Reset() {
	*x = MutateConfig{}
	mi := &file_mutate_config_v1_mutate_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateConfig) ProtoMessage() {}

func (x *MutateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mutate_config_v1_mutate_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateConfig.ProtoReflect.Descriptor instead.
func (*MutateConfig) Descriptor() ([]byte, []int) {
	return file_mutate_config_v1_mutate_config_proto_rawDescGZIP(), []int{0}
}

func (x *MutateConfig) GetProtoconfRoot() string {
	if x != nil {
		return x.ProtoconfRoot
	}
	return ""
}

func (x *MutateConfig) GetProtoFile() string {
	if x != nil {
		return x.ProtoFile
	}
	return ""
}

func (x *MutateConfig) GetProtoMsg() string {
	if x != nil {
		return x.ProtoMsg
	}
	return ""
}

func (x *MutateConfig) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *MutateConfig) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *MutateConfig) GetMetadataStr() string {
	if x != nil {
		return x.MetadataStr
	}
	return ""
}

func (x *MutateConfig) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *MutateConfig) GetTlsCert() string {
	if x != nil {
		return x.TlsCert
	}
	return ""
}

func (x *MutateConfig) GetTlsKey() string {
	if x != nil {
		return x.TlsKey
	}
	return ""
}

func (x *MutateConfig) GetTlsCa() string {
	if x != nil {
		return x.TlsCa
	}
	return ""
}

func (x *MutateConfig) GetInsecureTls() bool {
	if x != nil {
		return x.InsecureTls
	}
	return false
}

var File_mutate_config_v1_mutate_config_proto protoreflect.FileDescriptor

const file_mutate_config_v1_mutate_config_proto_rawDesc = "" +
	"\n" +
	"$mutate/config/v1/mutate_config.proto\x12\x1aprotoconf.mutate.config.v1\"\xbd\x02\n" +
	"\fMutateConfig\x12\x1c\n" +
	"\x0eprotoconf_root\x18\x01 \x01(\tR\x04root\x12\x19\n" +
	"\n" +
	"proto_file\x18\x02 \x01(\tR\x05proto\x12\x16\n" +
	"\tproto_msg\x18\x03 \x01(\tR\x03msg\x12\x1c\n" +
	"\x0eserver_address\x18\x04 \x01(\tR\x04addr\x12\x19\n" +
	"\vconfig_path\x18\x05 \x01(\tR\x04path\x12\x1e\n" +
	"\fmetadata_str\x18\x06 \x01(\tR\bmetadata\x12\x15\n" +
	"\x06fields\x18\a \x03(\tR\x05field\x12\x1a\n" +
	"\btls_cert\x18\b \x01(\tR\btls-cert\x12\x18\n" +
	"\atls_key\x18\t \x01(\tR\atls-key\x12\x16\n" +
	"\x06tls_ca\x18\n" +
	" \x01(\tR\x06tls-ca\x12\x1e\n" +
	"\finsecure_tls\x18\v \x01(\bR\binsecureBIZGgithub.com/protoconf/protoconf/mutate/config/v1;protoconf_mutate_configb\x06proto3"

var (
	file_mutate_config_v1_mutate_config_proto_rawDescOnce sync.Once
	file_mutate_config_v1_mutate_config_proto_rawDescData []byte
)

func file_mutate_config_v1_mutate_config_proto_rawDescGZIP() []byte {
	file_mutate_config_v1_mutate_config_proto_rawDescOnce.Do(func() {
		file_mutate_config_v1_mutate_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mutate_config_v1_mutate_config_proto_rawDesc), len(file_mutate_config_v1_mutate_config_proto_rawDesc)))
	})
	return file_mutate_config_v1_mutate_config_proto_rawDescData
}

var file_mutate_config_v1_mutate_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mutate_config_v1_mutate_config_proto_goTypes = []any{
	(*MutateConfig)(nil), // 0: protoconf.mutate.config.v1.MutateConfig
}
var file_mutate_config_v1_mutate_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mutate_config_v1_mutate_config_proto_init() }
func file_mutate_config_v1_mutate_config_proto_init() {
	if File_mutate_config_v1_mutate_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mutate_config_v1_mutate_config_proto_rawDesc), len(file_mutate_config_v1_mutate_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mutate_config_v1_mutate_config_proto_goTypes,
		DependencyIndexes: file_mutate_config_v1_mutate_config_proto_depIdxs,
		MessageInfos:      file_mutate_config_v1_mutate_config_proto_msgTypes,
	}.Build()
	File_mutate_config_v1_mutate_config_proto = out.File
	file_mutate_config_v1_mutate_config_proto_goTypes = nil
	file_mutate_config_v1_mutate_config_proto_depIdxs = nil
}
