// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: server/api/proto/v1/protoconf_mutation.proto

package protoconfmutation

import (
	v1 "github.com/protoconf/protoconf/datatypes/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigMutationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value          *v1.ProtoconfValue     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ScriptMetadata string                 `protobuf:"bytes,3,opt,name=script_metadata,json=scriptMetadata,proto3" json:"script_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigMutationRequest) Reset() {
	*x = ConfigMutationRequest{}
	mi := &file_server_api_proto_v1_protoconf_mutation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMutationRequest) ProtoMessage() {}

func (x *ConfigMutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_v1_protoconf_mutation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMutationRequest.ProtoReflect.Descriptor instead.
func (*ConfigMutationRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_v1_protoconf_mutation_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMutationRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigMutationRequest) GetValue() *v1.ProtoconfValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigMutationRequest) GetScriptMetadata() string {
	if x != nil {
		return x.ScriptMetadata
	}
	return ""
}

type ConfigMutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMutationResponse) Reset() {
	*x = ConfigMutationResponse{}
	mi := &file_server_api_proto_v1_protoconf_mutation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMutationResponse) ProtoMessage() {}

func (x *ConfigMutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_v1_protoconf_mutation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMutationResponse.ProtoReflect.Descriptor instead.
func (*ConfigMutationResponse) Descriptor() ([]byte, []int) {
	return file_server_api_proto_v1_protoconf_mutation_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigMutationResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigMutationResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

var File_server_api_proto_v1_protoconf_mutation_proto protoreflect.FileDescriptor

const file_server_api_proto_v1_protoconf_mutation_proto_rawDesc = "" +
	"\n" +
	",server/api/proto/v1/protoconf_mutation.proto\x12\x02v1\x1a(datatypes/proto/v1/protoconf_value.proto\"~\n" +
	"\x15ConfigMutationRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.v1.ProtoconfValueR\x05value\x12'\n" +
	"\x0fscript_metadata\x18\x03 \x01(\tR\x0escriptMetadata\"M\n" +
	"\x16ConfigMutationResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash2a\n" +
	"\x18ProtoconfMutationService\x12E\n" +
	"\fMutateConfig\x12\x19.v1.ConfigMutationRequest\x1a\x1a.v1.ConfigMutationResponseBc\n" +
	"\x1bcom.protoconf.server.api.v1ZDgithub.com/protoconf/protoconf/server/api/proto/v1;protoconfmutationb\x06proto3"

var (
	file_server_api_proto_v1_protoconf_mutation_proto_rawDescOnce sync.Once
	file_server_api_proto_v1_protoconf_mutation_proto_rawDescData []byte
)

func file_server_api_proto_v1_protoconf_mutation_proto_rawDescGZIP() []byte {
	file_server_api_proto_v1_protoconf_mutation_proto_rawDescOnce.Do(func() {
		file_server_api_proto_v1_protoconf_mutation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_proto_v1_protoconf_mutation_proto_rawDesc), len(file_server_api_proto_v1_protoconf_mutation_proto_rawDesc)))
	})
	return file_server_api_proto_v1_protoconf_mutation_proto_rawDescData
}

var file_server_api_proto_v1_protoconf_mutation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_api_proto_v1_protoconf_mutation_proto_goTypes = []any{
	(*ConfigMutationRequest)(nil),  // 0: v1.ConfigMutationRequest
	(*ConfigMutationResponse)(nil), // 1: v1.ConfigMutationResponse
	(*v1.ProtoconfValue)(nil),      // 2: v1.ProtoconfValue
}
var file_server_api_proto_v1_protoconf_mutation_proto_depIdxs = []int32{
	2, // 0: v1.ConfigMutationRequest.value:type_name -> v1.ProtoconfValue
	0, // 1: v1.ProtoconfMutationService.MutateConfig:input_type -> v1.ConfigMutationRequest
	1, // 2: v1.ProtoconfMutationService.MutateConfig:output_type -> v1.ConfigMutationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_api_proto_v1_protoconf_mutation_proto_init() }
func file_server_api_proto_v1_protoconf_mutation_proto_init() {
	if File_server_api_proto_v1_protoconf_mutation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_proto_v1_protoconf_mutation_proto_rawDesc), len(file_server_api_proto_v1_protoconf_mutation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_proto_v1_protoconf_mutation_proto_goTypes,
		DependencyIndexes: file_server_api_proto_v1_protoconf_mutation_proto_depIdxs,
		MessageInfos:      file_server_api_proto_v1_protoconf_mutation_proto_msgTypes,
	}.Build()
	File_server_api_proto_v1_protoconf_mutation_proto = out.File
	file_server_api_proto_v1_protoconf_mutation_proto_goTypes = nil
	file_server_api_proto_v1_protoconf_mutation_proto_depIdxs = nil
}
