#!/bin/bash

CURRENT_RELEASE=v$(cat VERSION)

git_rev=$(git rev-parse HEAD)

echo "BUILD_SCM_REVISION ${git_rev}"

git_tag="$(git tag --contains HEAD)"
if [[ "${CURRENT_RELEASE}" == "${git_tag}" ]] && git diff-index --quiet HEAD --; then
  echo "BUILD_SCM_TAG ${git_tag}"
  echo "STABLE_SCM_RELEASE ${git_tag}"
else
  echo "STABLE_SCM_RELEASE ${CURRENT_RELEASE}-${git_rev}"
fi
