#!/bin/bash


CURRENT_RELEASE="0.1.0"

# set -eu
# https://stackoverflow.com/a/4025065
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}


git_rev=$(git rev-parse HEAD)

echo "BUILD_SCM_REVISION ${git_rev}"

git_tag="$(git tag --contains HEAD)"
if vercomp "${CURRENT_RELEASE}" "${git_tag}" && git diff-index --quiet HEAD --; then
  echo "BUILD_SCM_TAG ${git_tag}"
  echo "STABLE_SCM_RELEASE ${git_tag}"
else
  postfix="${BUILDABLEREVISION:-$git_rev}.${BUILDABLEDIFF:-0}"
  echo "STABLE_SCM_RELEASE ${CURRENT_RELEASE}-${postfix}"
fi
