name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Run coverage
      run: export GOROOT=$(go env GOROOT); go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
