name: Go

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Run coverage
        run: export GOROOT=$(go env GOROOT); go test -race -coverprofile=coverage.txt -covermode=atomic -v ./... -json > test_results.json

      - name: Test report
        if: always()
        run: go run gotest.tools/gotestsum@v1.13.0 --format testdox --raw-command -- cat test_results.json

      - name: Upload Go test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: test_results.json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
            token: ${{ secrets.CODECOV_TOKEN }}