// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: inserter/config/v1/inserter_config.proto

package protoconf_inserter_config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreType enumerates supported key-value store backends.
type InserterConfig_StoreType int32

const (
	InserterConfig_consul     InserterConfig_StoreType = 0
	InserterConfig_etcd       InserterConfig_StoreType = 1
	InserterConfig_zookeeper  InserterConfig_StoreType = 2
	InserterConfig_configmaps InserterConfig_StoreType = 3
)

// Enum value maps for InserterConfig_StoreType.
var (
	InserterConfig_StoreType_name = map[int32]string{
		0: "consul",
		1: "etcd",
		2: "zookeeper",
		3: "configmaps",
	}
	InserterConfig_StoreType_value = map[string]int32{
		"consul":     0,
		"etcd":       1,
		"zookeeper":  2,
		"configmaps": 3,
	}
)

func (x InserterConfig_StoreType) Enum() *InserterConfig_StoreType {
	p := new(InserterConfig_StoreType)
	*p = x
	return p
}

func (x InserterConfig_StoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InserterConfig_StoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_inserter_config_v1_inserter_config_proto_enumTypes[0].Descriptor()
}

func (InserterConfig_StoreType) Type() protoreflect.EnumType {
	return &file_inserter_config_v1_inserter_config_proto_enumTypes[0]
}

func (x InserterConfig_StoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InserterConfig_StoreType.Descriptor instead.
func (InserterConfig_StoreType) EnumDescriptor() ([]byte, []int) {
	return file_inserter_config_v1_inserter_config_proto_rawDescGZIP(), []int{0, 0}
}

// InserterConfig defines the configuration for the protoconf inserter.
type InserterConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key-value store type.
	Store InserterConfig_StoreType `protobuf:"varint,1,opt,name=store,proto3,enum=protoconf.inserter.config.v1.InserterConfig_StoreType" json:"store,omitempty"`
	// Key-value store addresses (supports multiple addresses).
	StoreAddress []string `protobuf:"bytes,2,rep,name=store_address,json=store-address,proto3" json:"store_address,omitempty"`
	// Key-value store key prefix.
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Kubernetes namespace for ConfigMaps insertion.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Delete a config from the key-value store instead of inserting.
	Delete        bool `protobuf:"varint,5,opt,name=delete,json=d,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InserterConfig) Reset() {
	*x = InserterConfig{}
	mi := &file_inserter_config_v1_inserter_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InserterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InserterConfig) ProtoMessage() {}

func (x *InserterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_inserter_config_v1_inserter_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InserterConfig.ProtoReflect.Descriptor instead.
func (*InserterConfig) Descriptor() ([]byte, []int) {
	return file_inserter_config_v1_inserter_config_proto_rawDescGZIP(), []int{0}
}

func (x *InserterConfig) GetStore() InserterConfig_StoreType {
	if x != nil {
		return x.Store
	}
	return InserterConfig_consul
}

func (x *InserterConfig) GetStoreAddress() []string {
	if x != nil {
		return x.StoreAddress
	}
	return nil
}

func (x *InserterConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *InserterConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InserterConfig) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

var File_inserter_config_v1_inserter_config_proto protoreflect.FileDescriptor

const file_inserter_config_v1_inserter_config_proto_rawDesc = "" +
	"\n" +
	"(inserter/config/v1/inserter_config.proto\x12\x1cprotoconf.inserter.config.v1\"\x8f\x02\n" +
	"\x0eInserterConfig\x12L\n" +
	"\x05store\x18\x01 \x01(\x0e26.protoconf.inserter.config.v1.InserterConfig.StoreTypeR\x05store\x12$\n" +
	"\rstore_address\x18\x02 \x03(\tR\rstore-address\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x11\n" +
	"\x06delete\x18\x05 \x01(\bR\x01d\"@\n" +
	"\tStoreType\x12\n" +
	"\n" +
	"\x06consul\x10\x00\x12\b\n" +
	"\x04etcd\x10\x01\x12\r\n" +
	"\tzookeeper\x10\x02\x12\x0e\n" +
	"\n" +
	"configmaps\x10\x03BMZKgithub.com/protoconf/protoconf/inserter/config/v1;protoconf_inserter_configb\x06proto3"

var (
	file_inserter_config_v1_inserter_config_proto_rawDescOnce sync.Once
	file_inserter_config_v1_inserter_config_proto_rawDescData []byte
)

func file_inserter_config_v1_inserter_config_proto_rawDescGZIP() []byte {
	file_inserter_config_v1_inserter_config_proto_rawDescOnce.Do(func() {
		file_inserter_config_v1_inserter_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inserter_config_v1_inserter_config_proto_rawDesc), len(file_inserter_config_v1_inserter_config_proto_rawDesc)))
	})
	return file_inserter_config_v1_inserter_config_proto_rawDescData
}

var file_inserter_config_v1_inserter_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inserter_config_v1_inserter_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inserter_config_v1_inserter_config_proto_goTypes = []any{
	(InserterConfig_StoreType)(0), // 0: protoconf.inserter.config.v1.InserterConfig.StoreType
	(*InserterConfig)(nil),        // 1: protoconf.inserter.config.v1.InserterConfig
}
var file_inserter_config_v1_inserter_config_proto_depIdxs = []int32{
	0, // 0: protoconf.inserter.config.v1.InserterConfig.store:type_name -> protoconf.inserter.config.v1.InserterConfig.StoreType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inserter_config_v1_inserter_config_proto_init() }
func file_inserter_config_v1_inserter_config_proto_init() {
	if File_inserter_config_v1_inserter_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inserter_config_v1_inserter_config_proto_rawDesc), len(file_inserter_config_v1_inserter_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inserter_config_v1_inserter_config_proto_goTypes,
		DependencyIndexes: file_inserter_config_v1_inserter_config_proto_depIdxs,
		EnumInfos:         file_inserter_config_v1_inserter_config_proto_enumTypes,
		MessageInfos:      file_inserter_config_v1_inserter_config_proto_msgTypes,
	}.Build()
	File_inserter_config_v1_inserter_config_proto = out.File
	file_inserter_config_v1_inserter_config_proto_goTypes = nil
	file_inserter_config_v1_inserter_config_proto_depIdxs = nil
}
